{
  "version": "4.28.0",
  "time": 52.653,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "fl_compras_empenho",
        "title": "Compras - Empenho",
        "path": "data/fl_compras_empenho.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_processo",
              "title": "Número do Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_elemento",
              "title": "Elemento de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dotacao_orcamentaria",
              "title": "Dotação Orçamentária",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true,
                "pattern": "\\d{4} \\d{2}.\\d{3}.\\d{3}.\\d{4}.\\d{1} \\d{1}.\\d{1}.\\d{2}.\\d{2}.\\d{2} \\d{1}.\\d{2}.\\d{1}"
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_elemento"
              ],
              "reference": {
                "fields": [
                  "id_elemento"
                ],
                "resource": "dm_elemento_desp"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_compras_empenho"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "fl_compras_empenho"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "e907c846f9bec6f90d215dae88fe3938",
          "bytes": 9494927,
          "fields": 7,
          "rows": 924685
        }
      },
      "time": 52.653,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "367572",
            "13361318",
            "14302",
            "56162",
            "534",
            "2954",
            "1250 10.302.037.2023.1 3.3.90.39.61 0.49.2"
          ],
          "rowNumber": 214402,
          "rowPosition": 214403,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367572\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"214403\" violates the foreign key: for \"id_processo\": values \"367572\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367631",
            "13361421",
            "14390",
            "56714",
            "546",
            "3067",
            "2270 10.122.705.2500.1 3.3.90.40.02 0.10.1"
          ],
          "rowNumber": 395384,
          "rowPosition": 395385,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367631\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"395385\" violates the foreign key: for \"id_processo\": values \"367631\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13357056",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479369,
          "rowPosition": 479370,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479370\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13358083",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479370,
          "rowPosition": 479371,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479371\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13358084",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479371,
          "rowPosition": 479372,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479372\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13356877",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479372,
          "rowPosition": 479373,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479373\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13357057",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479373,
          "rowPosition": 479374,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479374\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13357228",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479374,
          "rowPosition": 479375,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479375\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13356878",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479375,
          "rowPosition": 479376,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479376\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13357734",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479376,
          "rowPosition": 479377,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479377\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13356879",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479378,
          "rowPosition": 479379,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479379\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13358085",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479424,
          "rowPosition": 479425,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479425\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13357407",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479425,
          "rowPosition": 479426,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479426\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367515",
            "13361422",
            "14334",
            "56432",
            "469",
            "2796",
            "2270 10.302.045.4174.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 479426,
          "rowPosition": 479427,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"479427\" violates the foreign key: for \"id_processo\": values \"367515\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367446",
            "13361399",
            "14334",
            "56432",
            "534",
            "3136",
            "2270 10.302.045.4174.1 3.3.90.39.98 0.10.1"
          ],
          "rowNumber": 485781,
          "rowPosition": 485782,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367446\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"485782\" violates the foreign key: for \"id_processo\": values \"367446\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367446",
            "13361400",
            "14334",
            "56432",
            "534",
            "3136",
            "2270 10.302.045.4174.1 3.3.90.39.98 0.10.1"
          ],
          "rowNumber": 485782,
          "rowPosition": 485783,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367446\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"485783\" violates the foreign key: for \"id_processo\": values \"367446\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367476",
            "13357185",
            "14301",
            "56614",
            "469",
            "2658",
            "1250 06.181.034.4048.1 3.3.90.30.19 0.10.1"
          ],
          "rowNumber": 825835,
          "rowPosition": 825836,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367476\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"825836\" violates the foreign key: for \"id_processo\": values \"367476\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367406",
            "13357280",
            "14304",
            "56144",
            "459",
            "2554",
            "1450 06.421.145.1058.1 4.4.90.52.12 1.10.8"
          ],
          "rowNumber": 826518,
          "rowPosition": 826519,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367406\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"826519\" violates the foreign key: for \"id_processo\": values \"367406\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367406",
            "13357096",
            "14304",
            "56144",
            "459",
            "2554",
            "1450 06.421.145.1058.1 4.4.90.52.12 1.10.8"
          ],
          "rowNumber": 826519,
          "rowPosition": 826520,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367406\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"826520\" violates the foreign key: for \"id_processo\": values \"367406\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367480",
            "13358082",
            "14353",
            "56157",
            "469",
            "3084",
            "1320 10.122.154.4437.1 3.3.90.30.03 0.10.1"
          ],
          "rowNumber": 827346,
          "rowPosition": 827347,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367480\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"827347\" violates the foreign key: for \"id_processo\": values \"367480\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367465",
            "13357071",
            "14353",
            "56244",
            "469",
            "2863",
            "1320 10.061.154.4441.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 829740,
          "rowPosition": 829741,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367465\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"829741\" violates the foreign key: for \"id_processo\": values \"367465\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367408",
            "13357072",
            "14353",
            "56244",
            "469",
            "2863",
            "1320 10.061.154.4441.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 829749,
          "rowPosition": 829750,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367408\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"829750\" violates the foreign key: for \"id_processo\": values \"367408\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367494",
            "13357247",
            "14353",
            "56244",
            "469",
            "2863",
            "1320 10.061.154.4441.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 829750,
          "rowPosition": 829751,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367494\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"829751\" violates the foreign key: for \"id_processo\": values \"367494\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367409",
            "13357248",
            "14353",
            "56244",
            "469",
            "2863",
            "1320 10.061.154.4441.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 829751,
          "rowPosition": 829752,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367409\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"829752\" violates the foreign key: for \"id_processo\": values \"367409\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367442",
            "13357246",
            "14353",
            "56244",
            "469",
            "2863",
            "1320 10.061.154.4441.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 829752,
          "rowPosition": 829753,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367442\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"829753\" violates the foreign key: for \"id_processo\": values \"367442\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367461",
            "13357024",
            "14301",
            "56506",
            "469",
            "2994",
            "1250 06.181.034.2032.1 3.3.90.30.17 0.10.1"
          ],
          "rowNumber": 830512,
          "rowPosition": 830513,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367461\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"830513\" violates the foreign key: for \"id_processo\": values \"367461\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367461",
            "13357702",
            "14301",
            "56506",
            "469",
            "2541",
            "1250 06.181.034.2032.1 3.3.90.30.22 0.10.1"
          ],
          "rowNumber": 830513,
          "rowPosition": 830514,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367461\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"830514\" violates the foreign key: for \"id_processo\": values \"367461\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367412",
            "13357510",
            "14295",
            "56313",
            "459",
            "2685",
            "1440 03.092.726.4150.1 4.4.90.52.04 0.10.1"
          ],
          "rowNumber": 833281,
          "rowPosition": 833282,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367412\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"833282\" violates the foreign key: for \"id_processo\": values \"367412\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367482",
            "13356842",
            "14302",
            "56162",
            "469",
            "2796",
            "1250 10.302.037.2023.1 3.3.90.30.13 0.49.2"
          ],
          "rowNumber": 833892,
          "rowPosition": 833893,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367482\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"833893\" violates the foreign key: for \"id_processo\": values \"367482\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367482",
            "13357374",
            "14302",
            "56162",
            "469",
            "2796",
            "1250 10.302.037.2023.1 3.3.90.30.13 0.49.2"
          ],
          "rowNumber": 833893,
          "rowPosition": 833894,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367482\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"833894\" violates the foreign key: for \"id_processo\": values \"367482\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367482",
            "13358046",
            "14302",
            "56162",
            "469",
            "2796",
            "1250 10.302.037.2023.1 3.3.90.30.13 0.49.2"
          ],
          "rowNumber": 833895,
          "rowPosition": 833896,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367482\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"833896\" violates the foreign key: for \"id_processo\": values \"367482\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367497",
            "13356843",
            "14302",
            "56162",
            "469",
            "2863",
            "1250 10.302.037.2023.1 3.3.90.30.12 0.49.2"
          ],
          "rowNumber": 833896,
          "rowPosition": 833897,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367497\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"833897\" violates the foreign key: for \"id_processo\": values \"367497\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367445",
            "13357526",
            "14353",
            "56157",
            "469",
            "2657",
            "1320 10.122.154.4437.1 3.3.90.30.05 0.10.1"
          ],
          "rowNumber": 841260,
          "rowPosition": 841261,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367445\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"841261\" violates the foreign key: for \"id_processo\": values \"367445\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367485",
            "13358023",
            "14353",
            "56157",
            "469",
            "2658",
            "1320 10.122.154.4437.1 3.3.90.30.19 0.10.1"
          ],
          "rowNumber": 841266,
          "rowPosition": 841267,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367485\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"841267\" violates the foreign key: for \"id_processo\": values \"367485\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367430",
            "13358201",
            "14353",
            "56157",
            "469",
            "3084",
            "1320 10.122.154.4437.1 3.3.90.30.03 0.10.1"
          ],
          "rowNumber": 841267,
          "rowPosition": 841268,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367430\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"841268\" violates the foreign key: for \"id_processo\": values \"367430\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367430",
            "13357004",
            "14353",
            "56157",
            "469",
            "3084",
            "1320 10.122.154.4437.1 3.3.90.30.03 0.10.1"
          ],
          "rowNumber": 841268,
          "rowPosition": 841269,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367430\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"841269\" violates the foreign key: for \"id_processo\": values \"367430\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367583",
            "13359435",
            "14303",
            "56510",
            "534",
            "3082",
            "1250 06.181.047.4106.1 3.3.90.39.39 0.10.1"
          ],
          "rowNumber": 879439,
          "rowPosition": 879440,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367583\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"879440\" violates the foreign key: for \"id_processo\": values \"367583\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367428",
            "13360532",
            "14302",
            "56162",
            "469",
            "2923",
            "1250 10.302.037.2023.1 3.3.90.30.10 0.49.2"
          ],
          "rowNumber": 880812,
          "rowPosition": 880813,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367428\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"880813\" violates the foreign key: for \"id_processo\": values \"367428\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367629",
            "13358284",
            "14301",
            "56787",
            "534",
            "2597",
            "1250 06.181.034.4057.1 3.3.90.39.31 0.73.1"
          ],
          "rowNumber": 883283,
          "rowPosition": 883284,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367629\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"883284\" violates the foreign key: for \"id_processo\": values \"367629\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367629",
            "13359837",
            "14301",
            "56787",
            "534",
            "2597",
            "1250 06.181.034.4057.1 3.3.90.39.31 0.73.1"
          ],
          "rowNumber": 883284,
          "rowPosition": 883285,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367629\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"883285\" violates the foreign key: for \"id_processo\": values \"367629\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367601",
            "13358684",
            "14301",
            "56787",
            "469",
            "3075",
            "1250 06.181.034.4057.1 3.3.90.30.01 0.73.1"
          ],
          "rowNumber": 883285,
          "rowPosition": 883286,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367601\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"883286\" violates the foreign key: for \"id_processo\": values \"367601\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367601",
            "13359838",
            "14301",
            "56787",
            "469",
            "2541",
            "1250 06.181.034.4057.1 3.3.90.30.22 0.73.1"
          ],
          "rowNumber": 883286,
          "rowPosition": 883287,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367601\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"883287\" violates the foreign key: for \"id_processo\": values \"367601\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367601",
            "13360956",
            "14301",
            "56787",
            "469",
            "2927",
            "1250 06.181.034.4057.1 3.3.90.30.25 0.73.1"
          ],
          "rowNumber": 883287,
          "rowPosition": 883288,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367601\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"883288\" violates the foreign key: for \"id_processo\": values \"367601\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367458",
            "13358617",
            "14390",
            "56878",
            "534",
            "2597",
            "1020 01.122.705.2009.1 3.3.90.39.31 0.10.1"
          ],
          "rowNumber": 884617,
          "rowPosition": 884618,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367458\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"884618\" violates the foreign key: for \"id_processo\": values \"367458\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367508",
            "13358389",
            "14420",
            "56642",
            "469",
            "2538",
            "1260 12.368.151.2074.1 3.3.90.30.08 0.23.1"
          ],
          "rowNumber": 886361,
          "rowPosition": 886362,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367508\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"886362\" violates the foreign key: for \"id_processo\": values \"367508\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367464",
            "13359916",
            "14353",
            "56244",
            "469",
            "2863",
            "1320 10.061.154.4441.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 886589,
          "rowPosition": 886590,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367464\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"886590\" violates the foreign key: for \"id_processo\": values \"367464\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367414",
            "13361046",
            "14353",
            "56244",
            "469",
            "2863",
            "1320 10.061.154.4441.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 886590,
          "rowPosition": 886591,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367414\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"886591\" violates the foreign key: for \"id_processo\": values \"367414\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367528",
            "13358782",
            "14353",
            "56244",
            "469",
            "2863",
            "1320 10.061.154.4441.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 886591,
          "rowPosition": 886592,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367528\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"886592\" violates the foreign key: for \"id_processo\": values \"367528\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367627",
            "13359917",
            "14353",
            "56244",
            "469",
            "2863",
            "1320 10.061.154.4441.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 886601,
          "rowPosition": 886602,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367627\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"886602\" violates the foreign key: for \"id_processo\": values \"367627\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367429",
            "13359761",
            "14403",
            "56586",
            "469",
            "2861",
            "1030 02.061.706.4395.1 3.3.90.30.04 0.77.1"
          ],
          "rowNumber": 894515,
          "rowPosition": 894516,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367429\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"894516\" violates the foreign key: for \"id_processo\": values \"367429\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367429",
            "13360110",
            "14403",
            "56586",
            "469",
            "2796",
            "1030 02.061.706.4395.1 3.3.90.30.13 0.77.1"
          ],
          "rowNumber": 894516,
          "rowPosition": 894517,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367429\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"894517\" violates the foreign key: for \"id_processo\": values \"367429\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367501",
            "13358592",
            "14403",
            "56586",
            "534",
            "2872",
            "1030 02.061.706.4395.1 3.3.90.39.10 0.77.1"
          ],
          "rowNumber": 894523,
          "rowPosition": 894524,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367501\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"894524\" violates the foreign key: for \"id_processo\": values \"367501\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367460",
            "13358628",
            "14390",
            "56714",
            "546",
            "3067",
            "1100 14.422.705.2500.1 3.3.90.40.02 0.10.1"
          ],
          "rowNumber": 896692,
          "rowPosition": 896693,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367460\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"896693\" violates the foreign key: for \"id_processo\": values \"367460\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367616",
            "13358608",
            "14353",
            "56157",
            "534",
            "2670",
            "1320 10.122.154.4437.1 3.3.90.39.21 0.10.1"
          ],
          "rowNumber": 897161,
          "rowPosition": 897162,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367616\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"897162\" violates the foreign key: for \"id_processo\": values \"367616\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367611",
            "13359374",
            "14353",
            "56157",
            "469",
            "2585",
            "1320 10.122.154.4437.1 3.3.90.30.27 0.10.1"
          ],
          "rowNumber": 897162,
          "rowPosition": 897163,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367611\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"897163\" violates the foreign key: for \"id_processo\": values \"367611\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367622",
            "13359375",
            "14353",
            "56157",
            "469",
            "3084",
            "1320 10.122.154.4437.1 3.3.90.30.03 0.10.1"
          ],
          "rowNumber": 897163,
          "rowPosition": 897164,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367622\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"897164\" violates the foreign key: for \"id_processo\": values \"367622\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367622",
            "13360865",
            "14353",
            "56157",
            "469",
            "2657",
            "1320 10.122.154.4437.1 3.3.90.30.05 0.10.1"
          ],
          "rowNumber": 897164,
          "rowPosition": 897165,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367622\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"897165\" violates the foreign key: for \"id_processo\": values \"367622\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367426",
            "13359369",
            "14353",
            "56157",
            "469",
            "3084",
            "1320 10.122.154.4437.1 3.3.90.30.03 0.10.1"
          ],
          "rowNumber": 897166,
          "rowPosition": 897167,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367426\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"897167\" violates the foreign key: for \"id_processo\": values \"367426\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367426",
            "13360856",
            "14353",
            "56157",
            "469",
            "2659",
            "1320 10.122.154.4437.1 3.3.90.30.21 0.10.1"
          ],
          "rowNumber": 897168,
          "rowPosition": 897169,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367426\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"897169\" violates the foreign key: for \"id_processo\": values \"367426\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367447",
            "13360263",
            "14353",
            "56157",
            "459",
            "2944",
            "1320 10.122.154.4437.1 4.4.90.52.14 0.10.1"
          ],
          "rowNumber": 897174,
          "rowPosition": 897175,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367447\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"897175\" violates the foreign key: for \"id_processo\": values \"367447\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367439",
            "13358196",
            "14353",
            "56157",
            "469",
            "3084",
            "1320 10.122.154.4437.1 3.3.90.30.03 0.10.1"
          ],
          "rowNumber": 897183,
          "rowPosition": 897184,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367439\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"897184\" violates the foreign key: for \"id_processo\": values \"367439\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367439",
            "13360863",
            "14353",
            "56157",
            "469",
            "3084",
            "1320 10.122.154.4437.1 3.3.90.30.03 0.10.1"
          ],
          "rowNumber": 897184,
          "rowPosition": 897185,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367439\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"897185\" violates the foreign key: for \"id_processo\": values \"367439\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367439",
            "13360864",
            "14353",
            "56157",
            "469",
            "3084",
            "1320 10.122.154.4437.1 3.3.90.30.03 0.10.1"
          ],
          "rowNumber": 897185,
          "rowPosition": 897186,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367439\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"897186\" violates the foreign key: for \"id_processo\": values \"367439\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367557",
            "13358744",
            "14390",
            "56714",
            "546",
            "3067",
            "2210 04.122.705.2500.1 3.3.90.40.02 0.60.1"
          ],
          "rowNumber": 898832,
          "rowPosition": 898833,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367557\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"898833\" violates the foreign key: for \"id_processo\": values \"367557\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367452",
            "13357054",
            "14334",
            "56432",
            "469",
            "2586",
            "2270 10.302.045.4174.1 3.3.90.30.30 0.10.1"
          ],
          "rowNumber": 899449,
          "rowPosition": 899450,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367452\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"899450\" violates the foreign key: for \"id_processo\": values \"367452\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367469",
            "13360251",
            "14342",
            "56475",
            "534",
            "2670",
            "2330 23.125.063.4127.1 3.3.90.39.21 0.73.1"
          ],
          "rowNumber": 899664,
          "rowPosition": 899665,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367469\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"899665\" violates the foreign key: for \"id_processo\": values \"367469\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367425",
            "13358769",
            "14423",
            "56847",
            "469",
            "2659",
            "2420 17.511.049.4094.1 3.3.90.30.21 1.10.8"
          ],
          "rowNumber": 900765,
          "rowPosition": 900766,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367425\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"900766\" violates the foreign key: for \"id_processo\": values \"367425\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367402",
            "13360671",
            "14390",
            "56714",
            "469",
            "2587",
            "1520 04.122.705.2500.1 3.3.90.30.31 0.10.1"
          ],
          "rowNumber": 901476,
          "rowPosition": 901477,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367402\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"901477\" violates the foreign key: for \"id_processo\": values \"367402\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367484",
            "13359195",
            "14304",
            "56144",
            "459",
            "2554",
            "1450 06.421.145.1058.1 4.4.90.52.12 1.10.8"
          ],
          "rowNumber": 903573,
          "rowPosition": 903574,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367484\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903574\" violates the foreign key: for \"id_processo\": values \"367484\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367484",
            "13358818",
            "14304",
            "56144",
            "459",
            "2944",
            "1450 06.421.145.1058.1 4.4.90.52.14 1.10.8"
          ],
          "rowNumber": 903574,
          "rowPosition": 903575,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367484\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903575\" violates the foreign key: for \"id_processo\": values \"367484\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367454",
            "13359932",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 903618,
          "rowPosition": 903619,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367454\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903619\" violates the foreign key: for \"id_processo\": values \"367454\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367477",
            "13360673",
            "14331",
            "56248",
            "469",
            "2923",
            "2010 10.302.011.4087.1 3.3.90.30.10 0.50.1"
          ],
          "rowNumber": 903619,
          "rowPosition": 903620,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367477\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903620\" violates the foreign key: for \"id_processo\": values \"367477\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367419",
            "13358801",
            "14331",
            "56248",
            "469",
            "2923",
            "2010 10.302.011.4087.1 3.3.90.30.10 0.50.1"
          ],
          "rowNumber": 903620,
          "rowPosition": 903621,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367419\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903621\" violates the foreign key: for \"id_processo\": values \"367419\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367502",
            "13361064",
            "14331",
            "56248",
            "469",
            "2995",
            "2010 10.302.011.4087.1 3.3.90.30.24 0.50.1"
          ],
          "rowNumber": 903621,
          "rowPosition": 903622,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367502\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903622\" violates the foreign key: for \"id_processo\": values \"367502\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367443",
            "13358802",
            "14331",
            "56248",
            "469",
            "2923",
            "2010 10.302.011.4087.1 3.3.90.30.10 0.50.1"
          ],
          "rowNumber": 903622,
          "rowPosition": 903623,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367443\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903623\" violates the foreign key: for \"id_processo\": values \"367443\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367418",
            "13360303",
            "14331",
            "56248",
            "469",
            "2923",
            "2010 10.302.011.4087.1 3.3.90.30.10 0.50.1"
          ],
          "rowNumber": 903623,
          "rowPosition": 903624,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367418\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903624\" violates the foreign key: for \"id_processo\": values \"367418\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367608",
            "13359538",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 903624,
          "rowPosition": 903625,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367608\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903625\" violates the foreign key: for \"id_processo\": values \"367608\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367549",
            "13358411",
            "14331",
            "56248",
            "469",
            "2923",
            "2010 10.302.011.4087.1 3.3.90.30.10 0.50.1"
          ],
          "rowNumber": 903625,
          "rowPosition": 903626,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367549\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903626\" violates the foreign key: for \"id_processo\": values \"367549\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367537",
            "13359539",
            "14331",
            "56248",
            "469",
            "2796",
            "2010 10.302.011.4087.1 3.3.90.30.13 0.50.1"
          ],
          "rowNumber": 903626,
          "rowPosition": 903627,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367537\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903627\" violates the foreign key: for \"id_processo\": values \"367537\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367546",
            "13359934",
            "14331",
            "56248",
            "469",
            "2796",
            "2010 10.302.011.4087.1 3.3.90.30.13 0.50.1"
          ],
          "rowNumber": 903627,
          "rowPosition": 903628,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367546\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903628\" violates the foreign key: for \"id_processo\": values \"367546\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367591",
            "13358811",
            "14331",
            "56816",
            "469",
            "2863",
            "2010 10.302.011.4083.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 903628,
          "rowPosition": 903629,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367591\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903629\" violates the foreign key: for \"id_processo\": values \"367591\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367538",
            "13358409",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 903629,
          "rowPosition": 903630,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367538\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903630\" violates the foreign key: for \"id_processo\": values \"367538\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367578",
            "13358410",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 903630,
          "rowPosition": 903631,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367578\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903631\" violates the foreign key: for \"id_processo\": values \"367578\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367555",
            "13358803",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 903631,
          "rowPosition": 903632,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367555\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903632\" violates the foreign key: for \"id_processo\": values \"367555\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367532",
            "13361065",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 903632,
          "rowPosition": 903633,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367532\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903633\" violates the foreign key: for \"id_processo\": values \"367532\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367573",
            "13358804",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 903633,
          "rowPosition": 903634,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367573\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903634\" violates the foreign key: for \"id_processo\": values \"367573\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367590",
            "13359933",
            "14331",
            "56248",
            "469",
            "2923",
            "2010 10.302.011.4087.1 3.3.90.30.10 0.50.1"
          ],
          "rowNumber": 903634,
          "rowPosition": 903635,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367590\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903635\" violates the foreign key: for \"id_processo\": values \"367590\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367521",
            "13360305",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 903635,
          "rowPosition": 903636,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367521\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903636\" violates the foreign key: for \"id_processo\": values \"367521\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367610",
            "13359935",
            "14331",
            "56248",
            "469",
            "2923",
            "2010 10.302.011.4087.1 3.3.90.30.10 0.50.1"
          ],
          "rowNumber": 903636,
          "rowPosition": 903637,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367610\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903637\" violates the foreign key: for \"id_processo\": values \"367610\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367575",
            "13359540",
            "14331",
            "56248",
            "469",
            "2923",
            "2010 10.302.011.4087.1 3.3.90.30.10 0.50.1"
          ],
          "rowNumber": 903637,
          "rowPosition": 903638,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367575\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903638\" violates the foreign key: for \"id_processo\": values \"367575\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367625",
            "13361066",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 903638,
          "rowPosition": 903639,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367625\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"903639\" violates the foreign key: for \"id_processo\": values \"367625\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367407",
            "13359142",
            "14334",
            "56626",
            "534",
            "3136",
            "2270 10.302.045.4178.1 3.3.90.39.98 0.10.1"
          ],
          "rowNumber": 904373,
          "rowPosition": 904374,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367407\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904374\" violates the foreign key: for \"id_processo\": values \"367407\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367413",
            "13358764",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 904895,
          "rowPosition": 904896,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904896\" violates the foreign key: for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367413",
            "13360645",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 904975,
          "rowPosition": 904976,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904976\" violates the foreign key: for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367413",
            "13358372",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 904976,
          "rowPosition": 904977,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904977\" violates the foreign key: for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367413",
            "13360275",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 904977,
          "rowPosition": 904978,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904978\" violates the foreign key: for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367413",
            "13359143",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 904978,
          "rowPosition": 904979,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904979\" violates the foreign key: for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367413",
            "13359512",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 904979,
          "rowPosition": 904980,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904980\" violates the foreign key: for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367413",
            "13359147",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 904980,
          "rowPosition": 904981,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904981\" violates the foreign key: for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367413",
            "13360277",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 904981,
          "rowPosition": 904982,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904982\" violates the foreign key: for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367413",
            "13359514",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 904982,
          "rowPosition": 904983,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904983\" violates the foreign key: for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367413",
            "13359515",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 904983,
          "rowPosition": 904984,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904984\" violates the foreign key: for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367413",
            "13358763",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 904984,
          "rowPosition": 904985,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"904985\" violates the foreign key: for \"id_processo\": values \"367413\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13358761",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 905475,
          "rowPosition": 905476,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905476\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13361029",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 905476,
          "rowPosition": 905477,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905477\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13360276",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 905477,
          "rowPosition": 905478,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905478\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13359144",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 905478,
          "rowPosition": 905479,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905479\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13359145",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 905479,
          "rowPosition": 905480,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905480\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13359146",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 905480,
          "rowPosition": 905481,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905481\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13358762",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 905481,
          "rowPosition": 905482,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905482\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13359513",
            "14334",
            "56163",
            "469",
            "2923",
            "2270 10.302.045.4177.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 905482,
          "rowPosition": 905483,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905483\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13359148",
            "14334",
            "56163",
            "469",
            "2863",
            "2270 10.302.045.4177.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 905483,
          "rowPosition": 905484,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905484\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13359149",
            "14334",
            "56163",
            "469",
            "2863",
            "2270 10.302.045.4177.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 905484,
          "rowPosition": 905485,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905485\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13360646",
            "14334",
            "56163",
            "469",
            "2863",
            "2270 10.302.045.4177.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 905485,
          "rowPosition": 905486,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905486\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367539",
            "13359516",
            "14334",
            "56163",
            "469",
            "2863",
            "2270 10.302.045.4177.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 905486,
          "rowPosition": 905487,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"905487\" violates the foreign key: for \"id_processo\": values \"367539\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367400",
            "13358375",
            "14334",
            "56163",
            "469",
            "2584",
            "2270 10.302.045.4177.1 3.3.90.30.16 0.10.1"
          ],
          "rowNumber": 906009,
          "rowPosition": 906010,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367400\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"906010\" violates the foreign key: for \"id_processo\": values \"367400\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367487",
            "13360630",
            "14369",
            "56492",
            "469",
            "2995",
            "1500 04.122.161.4482.1 3.3.90.30.24 0.10.1"
          ],
          "rowNumber": 906811,
          "rowPosition": 906812,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367487\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"906812\" violates the foreign key: for \"id_processo\": values \"367487\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367472",
            "13359517",
            "14334",
            "56719",
            "469",
            "2923",
            "2270 10.302.045.4063.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 907067,
          "rowPosition": 907068,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367472\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"907068\" violates the foreign key: for \"id_processo\": values \"367472\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367472",
            "13359903",
            "14334",
            "56719",
            "469",
            "2923",
            "2270 10.302.045.4063.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 907068,
          "rowPosition": 907069,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367472\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"907069\" violates the foreign key: for \"id_processo\": values \"367472\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367472",
            "13358373",
            "14334",
            "56719",
            "469",
            "2923",
            "2270 10.302.045.4063.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 907069,
          "rowPosition": 907070,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367472\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"907070\" violates the foreign key: for \"id_processo\": values \"367472\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367472",
            "13359905",
            "14334",
            "56719",
            "469",
            "2923",
            "2270 10.302.045.4063.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 907070,
          "rowPosition": 907071,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367472\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"907071\" violates the foreign key: for \"id_processo\": values \"367472\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367472",
            "13359904",
            "14334",
            "56719",
            "469",
            "2995",
            "2270 10.302.045.4063.1 3.3.90.30.24 0.10.1"
          ],
          "rowNumber": 907071,
          "rowPosition": 907072,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367472\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"907072\" violates the foreign key: for \"id_processo\": values \"367472\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367470",
            "13358395",
            "14417",
            "56537",
            "469",
            "2657",
            "2310 12.302.048.4180.1 3.3.90.30.05 0.10.1"
          ],
          "rowNumber": 907242,
          "rowPosition": 907243,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367470\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"907243\" violates the foreign key: for \"id_processo\": values \"367470\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367561",
            "13360288",
            "14417",
            "56537",
            "469",
            "2923",
            "2310 12.302.048.4180.1 3.3.90.30.10 0.10.1"
          ],
          "rowNumber": 907243,
          "rowPosition": 907244,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367561\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"907244\" violates the foreign key: for \"id_processo\": values \"367561\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367491",
            "13357559",
            "14390",
            "56714",
            "546",
            "3067",
            "2330 04.122.705.2500.1 3.3.90.40.02 0.73.1"
          ],
          "rowNumber": 918957,
          "rowPosition": 918958,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367491\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"918958\" violates the foreign key: for \"id_processo\": values \"367491\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367492",
            "13358125",
            "14331",
            "56816",
            "469",
            "2863",
            "2010 10.302.011.4083.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 919043,
          "rowPosition": 919044,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367492\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"919044\" violates the foreign key: for \"id_processo\": values \"367492\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367436",
            "13357939",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 919044,
          "rowPosition": 919045,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367436\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"919045\" violates the foreign key: for \"id_processo\": values \"367436\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367498",
            "13357940",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 919045,
          "rowPosition": 919046,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367498\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"919046\" violates the foreign key: for \"id_processo\": values \"367498\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367462",
            "13358118",
            "14331",
            "56248",
            "469",
            "2923",
            "2010 10.302.011.4087.1 3.3.90.30.10 0.50.1"
          ],
          "rowNumber": 919046,
          "rowPosition": 919047,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367462\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"919047\" violates the foreign key: for \"id_processo\": values \"367462\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367495",
            "13357436",
            "14331",
            "56248",
            "469",
            "2863",
            "2010 10.302.011.4087.1 3.3.90.30.12 0.50.1"
          ],
          "rowNumber": 919047,
          "rowPosition": 919048,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367495\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"919048\" violates the foreign key: for \"id_processo\": values \"367495\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367514",
            "13356914",
            "14331",
            "56248",
            "469",
            "2923",
            "2010 10.302.011.4087.1 3.3.90.30.10 0.50.1"
          ],
          "rowNumber": 919048,
          "rowPosition": 919049,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367514\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"919049\" violates the foreign key: for \"id_processo\": values \"367514\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367493",
            "13357745",
            "14363",
            "56672",
            "534",
            "2670",
            "2370 20.609.042.4443.1 3.3.90.39.21 1.91.1"
          ],
          "rowNumber": 920362,
          "rowPosition": 920363,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367493\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"920363\" violates the foreign key: for \"id_processo\": values \"367493\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367433",
            "13356885",
            "14334",
            "56163",
            "459",
            "2813",
            "2270 10.302.045.4177.1 4.4.90.52.09 0.10.1"
          ],
          "rowNumber": 920659,
          "rowPosition": 920660,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367433\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"920660\" violates the foreign key: for \"id_processo\": values \"367433\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367441",
            "13357576",
            "14334",
            "56719",
            "469",
            "2863",
            "2270 10.302.045.4063.1 3.3.90.30.12 0.10.1"
          ],
          "rowNumber": 920681,
          "rowPosition": 920682,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367441\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"920682\" violates the foreign key: for \"id_processo\": values \"367441\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367404",
            "13358092",
            "14423",
            "56847",
            "469",
            "2659",
            "2420 17.511.049.4094.1 3.3.90.30.21 1.10.8"
          ],
          "rowNumber": 920772,
          "rowPosition": 920773,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367404\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"920773\" violates the foreign key: for \"id_processo\": values \"367404\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367404",
            "13357914",
            "14423",
            "56847",
            "469",
            "2659",
            "2420 17.511.049.4094.1 3.3.90.30.21 1.10.8"
          ],
          "rowNumber": 920773,
          "rowPosition": 920774,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367404\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"920774\" violates the foreign key: for \"id_processo\": values \"367404\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367488",
            "13356888",
            "14334",
            "56433",
            "469",
            "2538",
            "2270 10.302.045.4176.1 3.3.90.30.08 0.10.1"
          ],
          "rowNumber": 922309,
          "rowPosition": 922310,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367488\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"922310\" violates the foreign key: for \"id_processo\": values \"367488\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367488",
            "13357413",
            "14334",
            "56433",
            "469",
            "2538",
            "2270 10.302.045.4176.1 3.3.90.30.08 0.10.1"
          ],
          "rowNumber": 922310,
          "rowPosition": 922311,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367488\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"922311\" violates the foreign key: for \"id_processo\": values \"367488\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367471",
            "13357392",
            "14390",
            "56714",
            "546",
            "3067",
            "2170 04.122.705.2500.1 3.3.90.40.02 0.10.1"
          ],
          "rowNumber": 923319,
          "rowPosition": 923320,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367471\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"923320\" violates the foreign key: for \"id_processo\": values \"367471\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367481",
            "13357742",
            "14334",
            "56434",
            "469",
            "2796",
            "2270 10.302.045.4179.1 3.3.90.30.13 0.10.1"
          ],
          "rowNumber": 923374,
          "rowPosition": 923375,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367481\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"923375\" violates the foreign key: for \"id_processo\": values \"367481\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "367420",
            "13358086",
            "14334",
            "56433",
            "469",
            "2994",
            "2270 10.302.045.4176.1 3.3.90.30.17 0.10.1"
          ],
          "rowNumber": 924066,
          "rowPosition": 924067,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_processo\": values \"367420\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "message": "Row at position \"924067\" violates the foreign key: for \"id_processo\": values \"367420\" not found in the lookup table \"dm_processo\" as \"id_processo\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 141
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 141,
    "tasks": 1
  },
  "valid": false
}