{
  "version": "4.28.0",
  "time": 230.239,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "6cee8cadb2080bff4891f217c8856214",
          "bytes": 56309521,
          "fields": 27,
          "rows": 1842647
        }
      },
      "time": 230.239,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "50274",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "60154",
            "1",
            "10",
            "501",
            "1",
            "12910",
            "369020",
            "75270",
            "889",
            "1831307",
            "2586",
            "2842",
            "2021",
            "2022-05-13",
            "5000.0000",
            "0.4700",
            "2350.00",
            "0.4300",
            "2150.00",
            "2150.00"
          ],
          "rowNumber": 1798957,
          "rowPosition": 1798958,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75270\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1798958\" violates the foreign key: for \"id_contrato\": values \"75270\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50274",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "60154",
            "1",
            "10",
            "665",
            "13774",
            "18882",
            "369055",
            "75270",
            "889",
            "1831307",
            "2586",
            "3331",
            "2021",
            "2022-05-13",
            "800.0000",
            "57.3500",
            "45880.00",
            "36.5900",
            "29272.00",
            "29272.00"
          ],
          "rowNumber": 1799454,
          "rowPosition": 1799455,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75270\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799455\" violates the foreign key: for \"id_contrato\": values \"75270\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50274",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "60154",
            "1",
            "10",
            "501",
            "5144",
            "31606",
            "369055",
            "75270",
            "875",
            "1831307",
            "2586",
            "3331",
            "2021",
            "2022-05-13",
            "50.0000",
            "76.8900",
            "3844.50",
            "46.9800",
            "2349.00",
            "2349.00"
          ],
          "rowNumber": 1800030,
          "rowPosition": 1800031,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75270\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800031\" violates the foreign key: for \"id_contrato\": values \"75270\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43990",
            "4",
            "1831009",
            "1",
            "1",
            "1",
            "856",
            "71017",
            "1",
            "77",
            "479",
            "1837",
            "91512",
            "369526",
            "75264",
            "27",
            "1831808",
            "2602",
            "2413",
            "2022",
            "2022-05-19",
            "0.0000",
            "62740.0000",
            "62740.00",
            "54760.0000",
            "54760.00",
            "54760.00"
          ],
          "rowNumber": 1800052,
          "rowPosition": 1800053,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75264\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800053\" violates the foreign key: for \"id_contrato\": values \"75264\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43990",
            "4",
            "1831009",
            "1",
            "1",
            "1",
            "856",
            "71017",
            "1",
            "77",
            "479",
            "1837",
            "91512",
            "369526",
            "75264",
            "889",
            "1831808",
            "2602",
            "2413",
            "2022",
            "2022-05-19",
            "0.0000",
            "57120.0000",
            "57120.00",
            "55840.0000",
            "55840.00",
            "55840.00"
          ],
          "rowNumber": 1800053,
          "rowPosition": 1800054,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75264\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800054\" violates the foreign key: for \"id_contrato\": values \"75264\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44015",
            "2",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "19679",
            "1",
            "77",
            "479",
            "1836",
            "91508",
            "369524",
            "75275",
            "889",
            "1831808",
            "2602",
            "2045",
            "2022",
            "2022-05-19",
            "0.0000",
            "24712.9200",
            "24712.92",
            "24712.9200",
            "24712.92",
            "24712.92"
          ],
          "rowNumber": 1800503,
          "rowPosition": 1800504,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75275\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800504\" violates the foreign key: for \"id_contrato\": values \"75275\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50360",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "35397",
            "1",
            "42",
            "399",
            "562",
            "118901",
            "369618",
            "75261",
            "889",
            "1831334",
            "2923",
            "2081",
            "2022",
            "2022-05-20",
            "25.0000",
            "652.3500",
            "16308.75",
            "652.3500",
            "16308.75",
            "16308.75"
          ],
          "rowNumber": 1801884,
          "rowPosition": 1801885,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75261\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801885\" violates the foreign key: for \"id_contrato\": values \"75261\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50360",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "35397",
            "1",
            "42",
            "107",
            "8242",
            "8979",
            "369618",
            "75261",
            "889",
            "1831334",
            "2923",
            "2081",
            "2022",
            "2022-05-20",
            "12.0000",
            "580.0000",
            "6960.00",
            "220.0000",
            "2640.00",
            "2640.00"
          ],
          "rowNumber": 1801886,
          "rowPosition": 1801887,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75261\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801887\" violates the foreign key: for \"id_contrato\": values \"75261\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50360",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "20444",
            "1",
            "42",
            "399",
            "16010",
            "134100",
            "369618",
            "75267",
            "889",
            "1831334",
            "2923",
            "2081",
            "2022",
            "2022-05-20",
            "40.0000",
            "210.0000",
            "8400.00",
            "210.0000",
            "8400.00",
            "8400.00"
          ],
          "rowNumber": 1801887,
          "rowPosition": 1801888,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75267\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801888\" violates the foreign key: for \"id_contrato\": values \"75267\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50360",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "35397",
            "1",
            "42",
            "107",
            "8242",
            "8884",
            "369618",
            "75261",
            "889",
            "1831334",
            "2923",
            "2081",
            "2022",
            "2022-05-20",
            "12.0000",
            "580.0000",
            "6960.00",
            "220.0000",
            "2640.00",
            "2640.00"
          ],
          "rowNumber": 1801888,
          "rowPosition": 1801889,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75261\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801889\" violates the foreign key: for \"id_contrato\": values \"75261\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43949",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69089",
            "1",
            "69",
            "740",
            "13114",
            "147581",
            "369659",
            "75266",
            "1174",
            "1831312",
            "2538",
            "2081",
            "2022",
            "2022-05-20",
            "3800.0000",
            "20.0100",
            "76042.18",
            "18.0000",
            "68400.00",
            "68400.00"
          ],
          "rowNumber": 1801925,
          "rowPosition": 1801926,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75266\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801926\" violates the foreign key: for \"id_contrato\": values \"75266\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "887",
            "23503",
            "367265",
            "75273",
            "149",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "20.0000",
            "150.0000",
            "3000.00",
            "180.0000",
            "3600.00",
            "3600.00"
          ],
          "rowNumber": 1802266,
          "rowPosition": 1802267,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802267\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "5756",
            "16109",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "50.0000",
            "45.0000",
            "2250.00",
            "50.0000",
            "2500.00",
            "2500.00"
          ],
          "rowNumber": 1802267,
          "rowPosition": 1802268,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802268\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "19198",
            "22440",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "100.0000",
            "27.0000",
            "2700.00",
            "30.0000",
            "3000.00",
            "3000.00"
          ],
          "rowNumber": 1802268,
          "rowPosition": 1802269,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802269\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "10892",
            "15694",
            "367265",
            "75273",
            "1415",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "50.0000",
            "4.0600",
            "203.00",
            "2.0000",
            "100.00",
            "100.00"
          ],
          "rowNumber": 1802269,
          "rowPosition": 1802270,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802270\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "507",
            "5927",
            "34612",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "1090.0000",
            "38.0000",
            "41420.00",
            "35.0000",
            "38150.00",
            "38150.00"
          ],
          "rowNumber": 1802270,
          "rowPosition": 1802271,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802271\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "10892",
            "8028",
            "367265",
            "75273",
            "1415",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "50.0000",
            "4.0600",
            "203.00",
            "2.0000",
            "100.00",
            "100.00"
          ],
          "rowNumber": 1802552,
          "rowPosition": 1802553,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802553\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "15877",
            "234571",
            "367265",
            "75273",
            "1330",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "100.0000",
            "14.7000",
            "1470.00",
            "8.0000",
            "800.00",
            "800.00"
          ],
          "rowNumber": 1802553,
          "rowPosition": 1802554,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802554\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "507",
            "21582",
            "169930",
            "367265",
            "75273",
            "1917",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "29000.0000",
            "4.9900",
            "144710.00",
            "5.5000",
            "159500.00",
            "159500.00"
          ],
          "rowNumber": 1802554,
          "rowPosition": 1802555,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802555\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "3058",
            "8308",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "2000.0000",
            "4.2000",
            "8400.00",
            "4.0000",
            "8000.00",
            "8000.00"
          ],
          "rowNumber": 1802555,
          "rowPosition": 1802556,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802556\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "740",
            "13114",
            "147581",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "8000.0000",
            "19.9000",
            "159200.00",
            "17.0000",
            "136000.00",
            "136000.00"
          ],
          "rowNumber": 1802556,
          "rowPosition": 1802557,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802557\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "9243",
            "134062",
            "367265",
            "75273",
            "1852",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "15.0000",
            "16.0000",
            "240.00",
            "7.0000",
            "105.00",
            "105.00"
          ],
          "rowNumber": 1802557,
          "rowPosition": 1802558,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802558\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "5756",
            "12990",
            "367265",
            "75273",
            "1420",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "745.0000",
            "6.1900",
            "4611.55",
            "9.0000",
            "6705.00",
            "6705.00"
          ],
          "rowNumber": 1802558,
          "rowPosition": 1802559,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802559\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "3058",
            "20395",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "7000.0000",
            "4.1000",
            "28700.00",
            "3.2000",
            "22400.00",
            "22400.00"
          ],
          "rowNumber": 1802559,
          "rowPosition": 1802560,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802560\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "773",
            "3460",
            "129057",
            "367265",
            "75273",
            "1420",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "300.0000",
            "2.5000",
            "750.00",
            "3.0000",
            "900.00",
            "900.00"
          ],
          "rowNumber": 1802560,
          "rowPosition": 1802561,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802561\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "3058",
            "159952",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "9000.0000",
            "4.1000",
            "36900.00",
            "3.5000",
            "31500.00",
            "31500.00"
          ],
          "rowNumber": 1802561,
          "rowPosition": 1802562,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802562\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "9448",
            "137455",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "2000.0000",
            "9.5000",
            "19000.00",
            "18.0000",
            "36000.00",
            "36000.00"
          ],
          "rowNumber": 1802562,
          "rowPosition": 1802563,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802563\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "363",
            "15361",
            "129706",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "50.0000",
            "13.9000",
            "695.00",
            "30.0000",
            "1500.00",
            "1500.00"
          ],
          "rowNumber": 1802563,
          "rowPosition": 1802564,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802564\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "16525",
            "22536",
            "367265",
            "75273",
            "1330",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "10.0000",
            "31.0000",
            "310.00",
            "36.0000",
            "360.00",
            "360.00"
          ],
          "rowNumber": 1802564,
          "rowPosition": 1802565,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802565\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "773",
            "21619",
            "170793",
            "367265",
            "75273",
            "1544",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "14000.0000",
            "8.5000",
            "119000.00",
            "7.5000",
            "105000.00",
            "105000.00"
          ],
          "rowNumber": 1802565,
          "rowPosition": 1802566,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802566\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "16551",
            "23411",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "10.0000",
            "70.0000",
            "700.00",
            "99.9500",
            "999.50",
            "999.50"
          ],
          "rowNumber": 1802566,
          "rowPosition": 1802567,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802567\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "15877",
            "22375",
            "367265",
            "75273",
            "1330",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "600.0000",
            "2.7000",
            "1620.00",
            "3.0000",
            "1800.00",
            "1800.00"
          ],
          "rowNumber": 1802567,
          "rowPosition": 1802568,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802568\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "3289",
            "31685",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "50.0000",
            "6.9500",
            "347.50",
            "6.0000",
            "300.00",
            "300.00"
          ],
          "rowNumber": 1802568,
          "rowPosition": 1802569,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802569\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "507",
            "5927",
            "20193",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "1500.0000",
            "45.0000",
            "67500.00",
            "40.0000",
            "60000.00",
            "60000.00"
          ],
          "rowNumber": 1802569,
          "rowPosition": 1802570,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802570\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "19346",
            "145651",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "250.0000",
            "9.0000",
            "2250.00",
            "10.0000",
            "2500.00",
            "2500.00"
          ],
          "rowNumber": 1802570,
          "rowPosition": 1802571,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802571\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "169",
            "16594",
            "106075",
            "367265",
            "75273",
            "1596",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "500.0000",
            "6.0000",
            "3000.00",
            "6.5000",
            "3250.00",
            "3250.00"
          ],
          "rowNumber": 1802571,
          "rowPosition": 1802572,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802572\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "21581",
            "170044",
            "367265",
            "75273",
            "1544",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "50.0000",
            "5.5000",
            "275.00",
            "6.0000",
            "300.00",
            "300.00"
          ],
          "rowNumber": 1802572,
          "rowPosition": 1802573,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802573\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "1027",
            "27617",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "200.0000",
            "7.9900",
            "1598.00",
            "9.0000",
            "1800.00",
            "1800.00"
          ],
          "rowNumber": 1802573,
          "rowPosition": 1802574,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802574\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "8513",
            "53253",
            "367265",
            "75273",
            "112",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "150.0000",
            "55.0000",
            "8250.00",
            "70.0000",
            "10500.00",
            "10500.00"
          ],
          "rowNumber": 1802574,
          "rowPosition": 1802575,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802575\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "10892",
            "15611",
            "367265",
            "75273",
            "1415",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "50.0000",
            "4.0600",
            "203.00",
            "2.0000",
            "100.00",
            "100.00"
          ],
          "rowNumber": 1802575,
          "rowPosition": 1802576,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802576\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "15877",
            "23291",
            "367265",
            "75273",
            "1330",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "200.0000",
            "3.6000",
            "720.00",
            "4.0000",
            "800.00",
            "800.00"
          ],
          "rowNumber": 1802576,
          "rowPosition": 1802577,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802577\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "773",
            "21580",
            "170035",
            "367265",
            "75273",
            "1544",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "9150.0000",
            "23.0000",
            "210450.00",
            "20.0000",
            "183000.00",
            "183000.00"
          ],
          "rowNumber": 1802577,
          "rowPosition": 1802578,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802578\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "740",
            "13926",
            "79085",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "90.0000",
            "16.0000",
            "1440.00",
            "18.0000",
            "1620.00",
            "1620.00"
          ],
          "rowNumber": 1802578,
          "rowPosition": 1802579,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802579\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "363",
            "16343",
            "34709",
            "367265",
            "75273",
            "120",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "160.0000",
            "200.0400",
            "32006.40",
            "220.0000",
            "35200.00",
            "35200.00"
          ],
          "rowNumber": 1802579,
          "rowPosition": 1802580,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802580\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "3127",
            "17743",
            "367265",
            "75273",
            "1328",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "4600.0000",
            "4.3700",
            "20102.00",
            "3.5000",
            "16100.00",
            "16100.00"
          ],
          "rowNumber": 1802580,
          "rowPosition": 1802581,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802581\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "740",
            "2862",
            "5063",
            "367265",
            "75273",
            "1653",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "800.0000",
            "9.0000",
            "7200.00",
            "7.0000",
            "5600.00",
            "5600.00"
          ],
          "rowNumber": 1802581,
          "rowPosition": 1802582,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802582\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "10892",
            "15612",
            "367265",
            "75273",
            "1415",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "50.0000",
            "4.0600",
            "203.00",
            "2.0000",
            "100.00",
            "100.00"
          ],
          "rowNumber": 1802582,
          "rowPosition": 1802583,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802583\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "740",
            "16362",
            "16850",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "2300.0000",
            "3.6000",
            "8280.00",
            "5.0000",
            "11500.00",
            "11500.00"
          ],
          "rowNumber": 1802583,
          "rowPosition": 1802584,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802584\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "21581",
            "170046",
            "367265",
            "75273",
            "1544",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "7000.0000",
            "23.0000",
            "161000.00",
            "20.0000",
            "140000.00",
            "140000.00"
          ],
          "rowNumber": 1802584,
          "rowPosition": 1802585,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802585\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "5558",
            "134695",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "6150.0000",
            "4.9900",
            "30688.50",
            "4.5000",
            "27675.00",
            "27675.00"
          ],
          "rowNumber": 1802585,
          "rowPosition": 1802586,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802586\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "15877",
            "22374",
            "367265",
            "75273",
            "1330",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "12100.0000",
            "2.4000",
            "29040.00",
            "3.0000",
            "36300.00",
            "36300.00"
          ],
          "rowNumber": 1802586,
          "rowPosition": 1802587,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802587\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "507",
            "13752",
            "103667",
            "367265",
            "75273",
            "1225",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "1200.0000",
            "3.5000",
            "4200.00",
            "3.5000",
            "4200.00",
            "4200.00"
          ],
          "rowNumber": 1802587,
          "rowPosition": 1802588,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802588\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "16525",
            "22535",
            "367265",
            "75273",
            "1330",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "10.0000",
            "25.5600",
            "255.60",
            "29.0000",
            "290.00",
            "290.00"
          ],
          "rowNumber": 1802588,
          "rowPosition": 1802589,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802589\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "363",
            "19036",
            "16113",
            "367265",
            "75273",
            "449",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "10250.0000",
            "10.6000",
            "108650.00",
            "12.0000",
            "123000.00",
            "123000.00"
          ],
          "rowNumber": 1802589,
          "rowPosition": 1802590,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802590\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "773",
            "21619",
            "170789",
            "367265",
            "75273",
            "1544",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "2400.0000",
            "8.5000",
            "20400.00",
            "8.0000",
            "19200.00",
            "19200.00"
          ],
          "rowNumber": 1802590,
          "rowPosition": 1802591,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802591\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "773",
            "8697",
            "23433",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "100.0000",
            "3.9000",
            "390.00",
            "6.0000",
            "600.00",
            "600.00"
          ],
          "rowNumber": 1802591,
          "rowPosition": 1802592,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802592\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "18892",
            "10485",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "50.0000",
            "8.1200",
            "406.00",
            "16.0000",
            "800.00",
            "800.00"
          ],
          "rowNumber": 1802592,
          "rowPosition": 1802593,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802593\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "363",
            "16343",
            "34709",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "1325.0000",
            "13.0000",
            "17225.00",
            "9.0000",
            "11925.00",
            "11925.00"
          ],
          "rowNumber": 1802593,
          "rowPosition": 1802594,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802594\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "740",
            "11441",
            "28499",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "370.0000",
            "16.5000",
            "6105.00",
            "10.0000",
            "3700.00",
            "3700.00"
          ],
          "rowNumber": 1802594,
          "rowPosition": 1802595,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802595\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "3128",
            "10585",
            "367265",
            "75273",
            "439",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "100.0000",
            "9.0000",
            "900.00",
            "7.0000",
            "700.00",
            "700.00"
          ],
          "rowNumber": 1802595,
          "rowPosition": 1802596,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802596\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "19037",
            "15408",
            "367265",
            "75273",
            "147",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "150.0000",
            "19.0000",
            "2850.00",
            "32.0000",
            "4800.00",
            "4800.00"
          ],
          "rowNumber": 1802596,
          "rowPosition": 1802597,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802597\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "8678",
            "128468",
            "367265",
            "75273",
            "455",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "130.0000",
            "6.4000",
            "832.00",
            "5.0000",
            "650.00",
            "650.00"
          ],
          "rowNumber": 1802597,
          "rowPosition": 1802598,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802598\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "11105",
            "28063",
            "367265",
            "75273",
            "433",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "130.0000",
            "10.4000",
            "1352.00",
            "5.0000",
            "650.00",
            "650.00"
          ],
          "rowNumber": 1802598,
          "rowPosition": 1802599,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802599\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "773",
            "8514",
            "15988",
            "367265",
            "75273",
            "112",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "1850.0000",
            "25.0000",
            "46250.00",
            "30.0000",
            "55500.00",
            "55500.00"
          ],
          "rowNumber": 1802599,
          "rowPosition": 1802600,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802600\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "773",
            "8646",
            "28498",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "300.0000",
            "15.0000",
            "4500.00",
            "15.0000",
            "4500.00",
            "4500.00"
          ],
          "rowNumber": 1802600,
          "rowPosition": 1802601,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802601\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "5726",
            "12097",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "150.0000",
            "10.5000",
            "1575.00",
            "15.0000",
            "2250.00",
            "2250.00"
          ],
          "rowNumber": 1802601,
          "rowPosition": 1802602,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802602\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "15877",
            "15347",
            "367265",
            "75273",
            "1330",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "200.0000",
            "7.1500",
            "1430.00",
            "4.0000",
            "800.00",
            "800.00"
          ],
          "rowNumber": 1802602,
          "rowPosition": 1802603,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802603\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "5756",
            "124959",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "415.0000",
            "29.0000",
            "12035.00",
            "30.0000",
            "12450.00",
            "12450.00"
          ],
          "rowNumber": 1802603,
          "rowPosition": 1802604,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802604\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "15877",
            "22376",
            "367265",
            "75273",
            "1330",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "24600.0000",
            "2.7000",
            "66420.00",
            "2.8300",
            "69618.00",
            "69618.00"
          ],
          "rowNumber": 1802604,
          "rowPosition": 1802605,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802605\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "773",
            "12585",
            "128475",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "600.0000",
            "5.6000",
            "3360.00",
            "7.0000",
            "4200.00",
            "4200.00"
          ],
          "rowNumber": 1802605,
          "rowPosition": 1802606,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802606\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "9243",
            "48182",
            "367265",
            "75273",
            "1852",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "15.0000",
            "4.0000",
            "60.00",
            "6.5000",
            "97.50",
            "97.50"
          ],
          "rowNumber": 1802606,
          "rowPosition": 1802607,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802607\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "507",
            "483",
            "7372",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "450.0000",
            "34.0000",
            "15300.00",
            "36.0000",
            "16200.00",
            "16200.00"
          ],
          "rowNumber": 1802607,
          "rowPosition": 1802608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802608\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "932",
            "23490",
            "367265",
            "75273",
            "1330",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "10.0000",
            "50.0000",
            "500.00",
            "60.0000",
            "600.00",
            "600.00"
          ],
          "rowNumber": 1802608,
          "rowPosition": 1802609,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802609\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "363",
            "8802",
            "104059",
            "367265",
            "75273",
            "439",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "200.0000",
            "29.0000",
            "5800.00",
            "30.0000",
            "6000.00",
            "6000.00"
          ],
          "rowNumber": 1802888,
          "rowPosition": 1802889,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802889\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "15877",
            "23293",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "600.0000",
            "12.5000",
            "7500.00",
            "8.0000",
            "4800.00",
            "4800.00"
          ],
          "rowNumber": 1802889,
          "rowPosition": 1802890,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802890\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "5558",
            "16844",
            "367265",
            "75273",
            "117",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "790.0000",
            "107.3400",
            "84798.60",
            "170.0000",
            "134300.00",
            "134300.00"
          ],
          "rowNumber": 1802890,
          "rowPosition": 1802891,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802891\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "18892",
            "16849",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "2850.0000",
            "4.9900",
            "14221.50",
            "4.5000",
            "12825.00",
            "12825.00"
          ],
          "rowNumber": 1802891,
          "rowPosition": 1802892,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802892\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "5558",
            "20390",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "2860.0000",
            "3.9900",
            "11411.40",
            "3.0000",
            "8580.00",
            "8580.00"
          ],
          "rowNumber": 1802892,
          "rowPosition": 1802893,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802893\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "773",
            "16500",
            "148132",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "200.0000",
            "4.8000",
            "960.00",
            "6.0000",
            "1200.00",
            "1200.00"
          ],
          "rowNumber": 1802893,
          "rowPosition": 1802894,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802894\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "3058",
            "119874",
            "367265",
            "75273",
            "1174",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "800.0000",
            "4.1000",
            "3280.00",
            "3.5000",
            "2800.00",
            "2800.00"
          ],
          "rowNumber": 1802894,
          "rowPosition": 1802895,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802895\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "1027",
            "127124",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "300.0000",
            "8.9900",
            "2697.00",
            "9.0000",
            "2700.00",
            "2700.00"
          ],
          "rowNumber": 1802895,
          "rowPosition": 1802896,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802896\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "16524",
            "148829",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "11.0000",
            "26.0000",
            "286.00",
            "14.0000",
            "154.00",
            "154.00"
          ],
          "rowNumber": 1802896,
          "rowPosition": 1802897,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802897\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "11286",
            "22441",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "1500.0000",
            "1.5000",
            "2250.00",
            "2.0000",
            "3000.00",
            "3000.00"
          ],
          "rowNumber": 1802897,
          "rowPosition": 1802898,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802898\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "446",
            "10892",
            "15610",
            "367265",
            "75273",
            "1415",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "50.0000",
            "4.0600",
            "203.00",
            "2.0000",
            "100.00",
            "100.00"
          ],
          "rowNumber": 1802898,
          "rowPosition": 1802899,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802899\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "667",
            "18753",
            "22439",
            "367265",
            "75273",
            "456",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "120.0000",
            "10.0000",
            "1200.00",
            "10.0000",
            "1200.00",
            "1200.00"
          ],
          "rowNumber": 1802899,
          "rowPosition": 1802900,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802900\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "342",
            "15877",
            "132496",
            "367265",
            "75273",
            "1330",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "200.0000",
            "3.8000",
            "760.00",
            "4.0000",
            "800.00",
            "800.00"
          ],
          "rowNumber": 1802900,
          "rowPosition": 1802901,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802901\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831022",
            "15",
            "1",
            "1",
            "338",
            "25220",
            "1",
            "69",
            "740",
            "13926",
            "23006",
            "367265",
            "75273",
            "98",
            "1831312",
            "2538",
            "3108",
            "2022",
            "2022-04-18",
            "5.0000",
            "31.0000",
            "155.00",
            "60.0100",
            "300.05",
            "300.05"
          ],
          "rowNumber": 1802901,
          "rowPosition": 1802902,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1802902\" violates the foreign key: for \"id_contrato\": values \"75273\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43976",
            "21",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "56531",
            "1",
            "58",
            "519",
            "17190",
            "200684",
            "367075",
            "75253",
            "889",
            "1831386",
            "2813",
            "3331",
            "2022",
            "2022-04-11",
            "1.0000",
            "471284.5000",
            "471284.50",
            "262892.7900",
            "262892.79",
            "262892.79"
          ],
          "rowNumber": 1820669,
          "rowPosition": 1820670,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75253\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820670\" violates the foreign key: for \"id_contrato\": values \"75253\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43976",
            "21",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "56531",
            "1",
            "58",
            "519",
            "17190",
            "200684",
            "367075",
            "75253",
            "889",
            "1831386",
            "2813",
            "3331",
            "2022",
            "2022-04-11",
            "4.0000",
            "471284.5000",
            "1885138.00",
            "262892.7900",
            "1051571.16",
            "1051571.16"
          ],
          "rowNumber": 1821533,
          "rowPosition": 1821534,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75253\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821534\" violates the foreign key: for \"id_contrato\": values \"75253\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50277",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "60894",
            "1",
            "42",
            "320",
            "15795",
            "162002",
            "367801",
            "75258",
            "889",
            "1831995",
            "2813",
            "2081",
            "2021",
            "2022-04-26",
            "30.0000",
            "1885.9900",
            "56579.70",
            "1000.0000",
            "30000.00",
            "30000.00"
          ],
          "rowNumber": 1824408,
          "rowPosition": 1824409,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75258\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824409\" violates the foreign key: for \"id_contrato\": values \"75258\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50277",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "59219",
            "1",
            "42",
            "320",
            "13442",
            "156869",
            "367801",
            "75254",
            "889",
            "1831995",
            "2813",
            "2081",
            "2021",
            "2022-04-26",
            "2.0000",
            "3799.9900",
            "7599.98",
            "3799.5000",
            "7599.00",
            "7599.00"
          ],
          "rowNumber": 1824409,
          "rowPosition": 1824410,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75254\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824410\" violates the foreign key: for \"id_contrato\": values \"75254\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50277",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "26877",
            "1",
            "42",
            "320",
            "13499",
            "165583",
            "367801",
            "75274",
            "889",
            "1831995",
            "2813",
            "2081",
            "2021",
            "2022-04-26",
            "6.0000",
            "1759.5000",
            "10557.00",
            "1759.5000",
            "10557.00",
            "10557.00"
          ],
          "rowNumber": 1824410,
          "rowPosition": 1824411,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75274\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824411\" violates the foreign key: for \"id_contrato\": values \"75274\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50277",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "16266",
            "1",
            "42",
            "320",
            "5253",
            "132608",
            "367801",
            "75272",
            "889",
            "1831995",
            "2813",
            "2081",
            "2021",
            "2022-04-26",
            "12.0000",
            "11655.3800",
            "139864.56",
            "11655.3800",
            "139864.56",
            "139864.56"
          ],
          "rowNumber": 1824414,
          "rowPosition": 1824415,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75272\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824415\" violates the foreign key: for \"id_contrato\": values \"75272\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50277",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "26877",
            "1",
            "42",
            "104",
            "14014",
            "28171",
            "367801",
            "75274",
            "889",
            "1831334",
            "2813",
            "2081",
            "2021",
            "2022-04-26",
            "6.0000",
            "126.0900",
            "756.56",
            "152.7900",
            "916.74",
            "916.74"
          ],
          "rowNumber": 1824415,
          "rowPosition": 1824416,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75274\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824416\" violates the foreign key: for \"id_contrato\": values \"75274\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50277",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "26877",
            "1",
            "42",
            "104",
            "20480",
            "113334",
            "367801",
            "75274",
            "889",
            "1831334",
            "2813",
            "2081",
            "2021",
            "2022-04-26",
            "5.0000",
            "94.9000",
            "474.50",
            "190.4500",
            "952.25",
            "952.25"
          ],
          "rowNumber": 1824416,
          "rowPosition": 1824417,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75274\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824417\" violates the foreign key: for \"id_contrato\": values \"75274\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50277",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "26877",
            "1",
            "42",
            "104",
            "2878",
            "123142",
            "367801",
            "75274",
            "889",
            "1831334",
            "2813",
            "2081",
            "2021",
            "2022-04-26",
            "5.0000",
            "302.0000",
            "1510.00",
            "126.2000",
            "631.00",
            "631.00"
          ],
          "rowNumber": 1824417,
          "rowPosition": 1824418,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75274\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824418\" violates the foreign key: for \"id_contrato\": values \"75274\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50360",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "20444",
            "1",
            "42",
            "399",
            "2244",
            "170224",
            "369618",
            "75263",
            "889",
            "1831334",
            "2923",
            "2081",
            "2022",
            "2022-05-24",
            "30.0000",
            "37.7900",
            "1133.70",
            "37.7900",
            "1133.70",
            "1133.70"
          ],
          "rowNumber": 1826791,
          "rowPosition": 1826792,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75263\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826792\" violates the foreign key: for \"id_contrato\": values \"75263\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50360",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "20444",
            "1",
            "42",
            "399",
            "14057",
            "30451",
            "369618",
            "75263",
            "889",
            "1831334",
            "2923",
            "2081",
            "2022",
            "2022-05-24",
            "60.0000",
            "146.1900",
            "8771.10",
            "108.3300",
            "6499.80",
            "6499.80"
          ],
          "rowNumber": 1826794,
          "rowPosition": 1826795,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75263\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826795\" violates the foreign key: for \"id_contrato\": values \"75263\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43961",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "70838",
            "1",
            "13",
            "110",
            "12814",
            "317512",
            "369226",
            "75269",
            "889",
            "1831958",
            "3019",
            "2082",
            "2022",
            "2022-05-16",
            "1.0000",
            "359500.0000",
            "359500.00",
            "294490.0000",
            "294490.00",
            "294490.00"
          ],
          "rowNumber": 1830285,
          "rowPosition": 1830286,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75269\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830286\" violates the foreign key: for \"id_contrato\": values \"75269\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43962",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "56",
            "7459",
            "1",
            "32",
            "103",
            "1054",
            "30972",
            "369418",
            "75259",
            "103",
            "1831313",
            "2608",
            "2925",
            "2022",
            "2022-05-18",
            "342.0000",
            "129.9000",
            "44425.80",
            "129.9000",
            "44425.80",
            "44425.80"
          ],
          "rowNumber": 1831191,
          "rowPosition": 1831192,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75259\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831192\" violates the foreign key: for \"id_contrato\": values \"75259\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43987",
            "14",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "20814",
            "1",
            "32",
            "100",
            "16012",
            "200125",
            "369386",
            "75260",
            "439",
            "1831400",
            "2796",
            "2082",
            "2022",
            "2022-05-18",
            "12.0000",
            "154.8300",
            "1857.96",
            "154.8300",
            "1857.96",
            "1857.96"
          ],
          "rowNumber": 1833620,
          "rowPosition": 1833621,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75260\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833621\" violates the foreign key: for \"id_contrato\": values \"75260\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50365",
            "14",
            "1831065",
            "65",
            "1",
            "1",
            "66",
            "31818",
            "1",
            "77",
            "533",
            "6893",
            "90378",
            "369160",
            "75257",
            "889",
            "1831594",
            "2804",
            "2884",
            "2022",
            "2022-05-16",
            "0.0000",
            "14010.0000",
            "14010.00",
            "9700.0000",
            "9700.00",
            "9700.00"
          ],
          "rowNumber": 1833722,
          "rowPosition": 1833723,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75257\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833723\" violates the foreign key: for \"id_contrato\": values \"75257\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50365",
            "4",
            "1831096",
            "92",
            "1",
            "1",
            "856",
            "56901",
            "1",
            "39",
            "710",
            "12521",
            "240579",
            "369473",
            "75262",
            "889",
            "1831805",
            "2670",
            "2631",
            "2022",
            "2022-05-18",
            "0.0000",
            "103008.0000",
            "103008.00",
            "39966.9600",
            "39966.96",
            "39966.96"
          ],
          "rowNumber": 1833753,
          "rowPosition": 1833754,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75262\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833754\" violates the foreign key: for \"id_contrato\": values \"75262\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "4",
            "1831009",
            "1",
            "1",
            "1",
            "61",
            "17774",
            "1",
            "77",
            "700",
            "17682",
            "93674",
            "369584",
            "75256",
            "981",
            "1831731",
            "2879",
            "2413",
            "2022",
            "2022-05-20",
            "0.0000",
            "104220.0000",
            "104220.00",
            "81777.3600",
            "81777.36",
            "81777.36"
          ],
          "rowNumber": 1839136,
          "rowPosition": 1839137,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75256\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1839137\" violates the foreign key: for \"id_contrato\": values \"75256\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43998",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "8192",
            "1",
            "42",
            "399",
            "16042",
            "167418",
            "369662",
            "75268",
            "889",
            "1831334",
            "2923",
            "2014",
            "2022",
            "2022-05-20",
            "270.0000",
            "90.0000",
            "24300.00",
            "90.0000",
            "24300.00",
            "24300.00"
          ],
          "rowNumber": 1839478,
          "rowPosition": 1839479,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75268\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1839479\" violates the foreign key: for \"id_contrato\": values \"75268\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43998",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "8192",
            "1",
            "42",
            "399",
            "16042",
            "166946",
            "369662",
            "75268",
            "889",
            "1831334",
            "2923",
            "2014",
            "2022",
            "2022-05-20",
            "270.0000",
            "90.0000",
            "24300.00",
            "90.0000",
            "24300.00",
            "24300.00"
          ],
          "rowNumber": 1839479,
          "rowPosition": 1839480,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75268\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1839480\" violates the foreign key: for \"id_contrato\": values \"75268\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43998",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "18679",
            "1",
            "42",
            "399",
            "19563",
            "36379",
            "369662",
            "75265",
            "889",
            "1831334",
            "2923",
            "2014",
            "2022",
            "2022-05-20",
            "48.0000",
            "720.0000",
            "34560.00",
            "720.0000",
            "34560.00",
            "34560.00"
          ],
          "rowNumber": 1839480,
          "rowPosition": 1839481,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75265\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1839481\" violates the foreign key: for \"id_contrato\": values \"75265\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43998",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "18679",
            "1",
            "42",
            "399",
            "16042",
            "130861",
            "369662",
            "75265",
            "889",
            "1831334",
            "2923",
            "2014",
            "2022",
            "2022-05-20",
            "30.0000",
            "760.0000",
            "22800.00",
            "720.0000",
            "21600.00",
            "21600.00"
          ],
          "rowNumber": 1839481,
          "rowPosition": 1839482,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75265\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1839482\" violates the foreign key: for \"id_contrato\": values \"75265\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43998",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "8192",
            "1",
            "42",
            "399",
            "10909",
            "66344",
            "369662",
            "75268",
            "889",
            "1831334",
            "2923",
            "2014",
            "2022",
            "2022-05-20",
            "9000.0000",
            "6.9000",
            "62100.00",
            "6.9000",
            "62100.00",
            "62100.00"
          ],
          "rowNumber": 1839482,
          "rowPosition": 1839483,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75268\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1839483\" violates the foreign key: for \"id_contrato\": values \"75268\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44017",
            "2",
            "1831016",
            "16",
            "1",
            "1",
            "883",
            "3962",
            "1",
            "9",
            "576",
            "17557",
            "168219",
            "369624",
            "75255",
            "889",
            "1831365",
            "2736",
            "2082",
            "2022",
            "2022-05-20",
            "0.0000",
            "335160.0000",
            "335160.00",
            "335160.0000",
            "335160.00",
            "335160.00"
          ],
          "rowNumber": 1840542,
          "rowPosition": 1840543,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75255\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1840543\" violates the foreign key: for \"id_contrato\": values \"75255\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43949",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "7098",
            "285334",
            "368962",
            "75271",
            "889",
            "1831812",
            "3065",
            "2014",
            "2022",
            "2022-05-12",
            "0.0000",
            "228000.0000",
            "228000.00",
            "228000.0000",
            "228000.00",
            "228000.00"
          ],
          "rowNumber": 1842122,
          "rowPosition": 1842123,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75271\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1842123\" violates the foreign key: for \"id_contrato\": values \"75271\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43949",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "7098",
            "98701",
            "368962",
            "75271",
            "889",
            "1831812",
            "3065",
            "2014",
            "2022",
            "2022-05-12",
            "0.0000",
            "25344.0000",
            "25344.00",
            "25344.0000",
            "25344.00",
            "25344.00"
          ],
          "rowNumber": 1842123,
          "rowPosition": 1842124,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75271\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1842124\" violates the foreign key: for \"id_contrato\": values \"75271\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43949",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "7098",
            "98700",
            "368962",
            "75271",
            "889",
            "1831812",
            "3065",
            "2014",
            "2022",
            "2022-05-12",
            "0.0000",
            "7260.0000",
            "7260.00",
            "7260.0000",
            "7260.00",
            "7260.00"
          ],
          "rowNumber": 1842124,
          "rowPosition": 1842125,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75271\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1842125\" violates the foreign key: for \"id_contrato\": values \"75271\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 113
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 113,
    "tasks": 1
  },
  "valid": false
}