{
  "version": "4.28.0",
  "time": 236.692,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "9a7f23996ae198cc296ac20815fa2f7a",
          "bytes": 56265542,
          "fields": 27,
          "rows": 1841088
        }
      },
      "time": 236.692,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "50367",
            "4",
            "1831079",
            "76",
            "1",
            "1",
            "563",
            "24316",
            "1",
            "17",
            "379",
            "17564",
            "94354",
            "367262",
            "75173",
            "1968",
            "1831449",
            "2613",
            "2046",
            "2022",
            "2022-04-18",
            "0.0000",
            "250000.0000",
            "250000.00",
            "250000.0000",
            "250000.00",
            "250000.00"
          ],
          "rowNumber": 1798671,
          "rowPosition": 1798672,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75173\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1798672\" violates the foreign key: for \"id_contrato\": values \"75173\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44008",
            "1",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "12185",
            "1",
            "26",
            "592",
            "21790",
            "181764",
            "369019",
            "75188",
            "1020",
            "1831291",
            "2863",
            "2078",
            "2022",
            "2022-05-13",
            "120.0000",
            "3699.8400",
            "443980.80",
            "3699.8400",
            "443980.80",
            "443980.80"
          ],
          "rowNumber": 1798687,
          "rowPosition": 1798688,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75188\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1798688\" violates the foreign key: for \"id_contrato\": values \"75188\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43959",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "52",
            "721",
            "480",
            "137377",
            "369044",
            "75192",
            "201",
            "1831189",
            "2796",
            "2842",
            "2022",
            "2022-05-13",
            "7.0000",
            "269.7700",
            "1888.39",
            "269.7700",
            "1888.39",
            "1888.39"
          ],
          "rowNumber": 1798985,
          "rowPosition": 1798986,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1798986\" violates the foreign key: for \"id_contrato\": values \"75192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "732",
            "2794",
            "80128",
            "369054",
            "75176",
            "889",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-05-13",
            "21.0000",
            "349.7400",
            "7344.54",
            "342.2800",
            "7187.88",
            "7187.88"
          ],
          "rowNumber": 1798986,
          "rowPosition": 1798987,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75176\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1798987\" violates the foreign key: for \"id_contrato\": values \"75176\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "732",
            "2794",
            "80128",
            "369037",
            "75176",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-05-13",
            "21.0000",
            "349.7400",
            "7344.54",
            "342.2800",
            "7187.88",
            "7187.88"
          ],
          "rowNumber": 1799455,
          "rowPosition": 1799456,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75176\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799456\" violates the foreign key: for \"id_contrato\": values \"75176\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44017",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "21269",
            "1",
            "17",
            "379",
            "9823",
            "94352",
            "369496",
            "75189",
            "889",
            "1831370",
            "2594",
            "1760",
            "2022",
            "2022-05-19",
            "0.0000",
            "848020.8000",
            "848020.80",
            "848020.8000",
            "848020.80",
            "737117.88"
          ],
          "rowNumber": 1799465,
          "rowPosition": 1799466,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75189\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799466\" violates the foreign key: for \"id_contrato\": values \"75189\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44017",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "21269",
            "1",
            "85",
            "414",
            "7784",
            "158667",
            "369496",
            "75189",
            "889",
            "1831980",
            "3088",
            "1760",
            "2022",
            "2022-05-19",
            "90.0000",
            "277.3600",
            "24962.40",
            "277.3600",
            "24962.40",
            "24962.40"
          ],
          "rowNumber": 1799466,
          "rowPosition": 1799467,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75189\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799467\" violates the foreign key: for \"id_contrato\": values \"75189\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44018",
            "15",
            "1910409",
            "59",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "2941",
            "5465",
            "369520",
            "75182",
            "190",
            "1831313",
            "2928",
            "2840",
            "2022",
            "2022-05-19",
            "5000.0000",
            "4.8200",
            "24101.50",
            "4.8200",
            "24101.50",
            "24101.50"
          ],
          "rowNumber": 1799469,
          "rowPosition": 1799470,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75182\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799470\" violates the foreign key: for \"id_contrato\": values \"75182\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43959",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "52",
            "721",
            "480",
            "137377",
            "369029",
            "75192",
            "201",
            "1831189",
            "2796",
            "3331",
            "2022",
            "2022-05-13",
            "1.0000",
            "269.7700",
            "269.77",
            "269.7700",
            "269.77",
            "269.77"
          ],
          "rowNumber": 1800017,
          "rowPosition": 1800018,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800018\" violates the foreign key: for \"id_contrato\": values \"75192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44012",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "502",
            "4032",
            "156228",
            "369127",
            "75178",
            "889",
            "1831296",
            "2944",
            "3293",
            "2022",
            "2022-05-13",
            "17.0000",
            "520.0000",
            "8840.00",
            "520.0000",
            "8840.00",
            "8840.00"
          ],
          "rowNumber": 1800027,
          "rowPosition": 1800028,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75178\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800028\" violates the foreign key: for \"id_contrato\": values \"75178\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44012",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "844",
            "23493",
            "1",
            "54",
            "502",
            "14376",
            "155896",
            "369127",
            "75178",
            "889",
            "1831296",
            "2944",
            "3293",
            "2022",
            "2022-05-13",
            "3.0000",
            "760.0000",
            "2280.00",
            "760.0000",
            "2280.00",
            "2280.00"
          ],
          "rowNumber": 1800028,
          "rowPosition": 1800029,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75178\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800029\" violates the foreign key: for \"id_contrato\": values \"75178\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "1",
            "1831047",
            "37",
            "1",
            "1",
            "66",
            "70903",
            "1",
            "77",
            "533",
            "4338",
            "90067",
            "369534",
            "75198",
            "889",
            "1831751",
            "2807",
            "3044",
            "2022",
            "2022-05-19",
            "0.0000",
            "200000.0000",
            "200000.00",
            "200000.0000",
            "200000.00",
            "200000.00"
          ],
          "rowNumber": 1800086,
          "rowPosition": 1800087,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75198\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800087\" violates the foreign key: for \"id_contrato\": values \"75198\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44018",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "35979",
            "1",
            "89",
            "778",
            "10128",
            "337999",
            "369549",
            "75207",
            "889",
            "1831991",
            "2743",
            "3043",
            "2022",
            "2022-05-19",
            "1.0000",
            "1860.0000",
            "1860.00",
            "1860.0000",
            "1860.00",
            "1860.00"
          ],
          "rowNumber": 1800492,
          "rowPosition": 1800493,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1800493\" violates the foreign key: for \"id_contrato\": values \"75207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "1",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "70962",
            "1",
            "77",
            "479",
            "1836",
            "91508",
            "368217",
            "75194",
            "889",
            "1831808",
            "2806",
            "1760",
            "2022",
            "2022-05-02",
            "0.0000",
            "4320.0000",
            "4320.00",
            "4320.0000",
            "4320.00",
            "4320.00"
          ],
          "rowNumber": 1801151,
          "rowPosition": 1801152,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1801152\" violates the foreign key: for \"id_contrato\": values \"75194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831071",
            "67",
            "1",
            "1",
            "66",
            "59706",
            "1",
            "77",
            "700",
            "9761",
            "93015",
            "369098",
            "75175",
            "889",
            "1831440",
            "2594",
            "3267",
            "2022",
            "2022-05-13",
            "0.0000",
            "15000.0000",
            "15000.00",
            "10000.0000",
            "10000.00",
            "10000.00"
          ],
          "rowNumber": 1803565,
          "rowPosition": 1803566,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1803566\" violates the foreign key: for \"id_contrato\": values \"75175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43956",
            "4",
            "1831071",
            "67",
            "1",
            "1",
            "66",
            "59706",
            "1",
            "77",
            "700",
            "17508",
            "92910",
            "369098",
            "75175",
            "889",
            "1831748",
            "2954",
            "3267",
            "2022",
            "2022-05-13",
            "0.0000",
            "17125.8000",
            "17125.80",
            "16999.9800",
            "16999.98",
            "16999.98"
          ],
          "rowNumber": 1803566,
          "rowPosition": 1803567,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1803567\" violates the foreign key: for \"id_contrato\": values \"75175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50282",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "33058",
            "1",
            "32",
            "100",
            "247",
            "3474",
            "368144",
            "75195",
            "1099",
            "1831400",
            "2796",
            "3331",
            "2021",
            "2022-05-02",
            "104.0000",
            "321.0000",
            "33384.00",
            "260.0000",
            "27040.00",
            "27040.00"
          ],
          "rowNumber": 1805922,
          "rowPosition": 1805923,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75195\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805923\" violates the foreign key: for \"id_contrato\": values \"75195\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "306",
            "17797",
            "169393",
            "368615",
            "75204",
            "889",
            "1831295",
            "2584",
            "2045",
            "2022",
            "2022-05-09",
            "5.0000",
            "89.0000",
            "445.00",
            "194.5500",
            "972.75",
            "972.75"
          ],
          "rowNumber": 1805977,
          "rowPosition": 1805978,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805978\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "87",
            "540",
            "952",
            "336199",
            "368615",
            "75204",
            "889",
            "1831121",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "9900.0000",
            "9900.00",
            "2611.7100",
            "2611.71",
            "2611.71"
          ],
          "rowNumber": 1805978,
          "rowPosition": 1805979,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805979\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "30",
            "173",
            "12392",
            "93757",
            "368615",
            "75204",
            "889",
            "1831354",
            "2670",
            "2045",
            "2022",
            "2022-05-09",
            "0.0000",
            "25449.0000",
            "25449.00",
            "23233.4600",
            "23233.46",
            "23233.46"
          ],
          "rowNumber": 1805979,
          "rowPosition": 1805980,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805980\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "30",
            "173",
            "12392",
            "168220",
            "368615",
            "75204",
            "889",
            "1831354",
            "2670",
            "2045",
            "2022",
            "2022-05-09",
            "0.0000",
            "56311.9600",
            "56311.96",
            "21380.0000",
            "21380.00",
            "21380.00"
          ],
          "rowNumber": 1805980,
          "rowPosition": 1805981,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805981\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "535",
            "18171",
            "182199",
            "368615",
            "75204",
            "889",
            "1831991",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "16841.0000",
            "16841.00",
            "9368.1900",
            "9368.19",
            "9368.19"
          ],
          "rowNumber": 1805981,
          "rowPosition": 1805982,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805982\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "535",
            "2147",
            "182192",
            "368615",
            "75204",
            "889",
            "1831991",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "2.0000",
            "3476.1000",
            "6952.20",
            "1910.6700",
            "3821.34",
            "3821.34"
          ],
          "rowNumber": 1805982,
          "rowPosition": 1805983,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805983\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "535",
            "2147",
            "122547",
            "368615",
            "75204",
            "889",
            "1831991",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "2.0000",
            "3483.8700",
            "6967.74",
            "4727.0800",
            "9454.16",
            "9454.16"
          ],
          "rowNumber": 1805983,
          "rowPosition": 1805984,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805984\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "176",
            "18267",
            "287189",
            "368615",
            "75204",
            "889",
            "1831991",
            "2924",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "6958.7100",
            "6958.71",
            "5269.4200",
            "5269.42",
            "5269.42"
          ],
          "rowNumber": 1805984,
          "rowPosition": 1805985,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805985\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "248",
            "20376",
            "189985",
            "368615",
            "75204",
            "889",
            "1831991",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "2.0000",
            "20274.6300",
            "40549.26",
            "22336.2400",
            "44672.48",
            "44672.48"
          ],
          "rowNumber": 1805985,
          "rowPosition": 1805986,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805986\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "778",
            "4608",
            "189945",
            "368615",
            "75204",
            "889",
            "1831991",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "6538.0000",
            "6538.00",
            "5608.0200",
            "5608.02",
            "5608.02"
          ],
          "rowNumber": 1805986,
          "rowPosition": 1805987,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805987\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "437",
            "7956",
            "335942",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "2.0000",
            "14077.0000",
            "28154.00",
            "9746.2400",
            "19492.48",
            "19492.48"
          ],
          "rowNumber": 1805987,
          "rowPosition": 1805988,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805988\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "437",
            "7956",
            "127237",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "2.0000",
            "11115.5700",
            "22231.13",
            "4836.8400",
            "9673.68",
            "9673.68"
          ],
          "rowNumber": 1805988,
          "rowPosition": 1805989,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805989\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "437",
            "7956",
            "339066",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "18271.0000",
            "18271.00",
            "10024.3500",
            "10024.35",
            "10024.35"
          ],
          "rowNumber": 1805989,
          "rowPosition": 1805990,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805990\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "437",
            "7956",
            "64170",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "2.0000",
            "6936.0000",
            "13872.00",
            "6226.2200",
            "12452.44",
            "12452.44"
          ],
          "rowNumber": 1805990,
          "rowPosition": 1805991,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805991\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "437",
            "2793",
            "123995",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "16189.0000",
            "16189.00",
            "8352.9900",
            "8352.99",
            "8352.99"
          ],
          "rowNumber": 1805991,
          "rowPosition": 1805992,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805992\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "437",
            "2793",
            "337777",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "8606.2200",
            "8606.22",
            "9141.7500",
            "9141.75",
            "9141.75"
          ],
          "rowNumber": 1805992,
          "rowPosition": 1805993,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805993\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "437",
            "8969",
            "289396",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "6777.6800",
            "6777.68",
            "4543.7500",
            "4543.75",
            "4543.75"
          ],
          "rowNumber": 1805993,
          "rowPosition": 1805994,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805994\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "44",
            "724",
            "15676",
            "335943",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "3.0000",
            "6227.0100",
            "18681.03",
            "3021.6600",
            "9064.98",
            "9064.98"
          ],
          "rowNumber": 1805994,
          "rowPosition": 1805995,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805995\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "77",
            "533",
            "9643",
            "90741",
            "368615",
            "75204",
            "889",
            "1831749",
            "2738",
            "2045",
            "2022",
            "2022-05-09",
            "0.0000",
            "15033.0000",
            "15033.00",
            "15000.0000",
            "15000.00",
            "15000.00"
          ],
          "rowNumber": 1805995,
          "rowPosition": 1805996,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805996\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "627",
            "19215",
            "338809",
            "368615",
            "75204",
            "889",
            "1831295",
            "2611",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "29290.7000",
            "29290.70",
            "32584.0100",
            "32584.01",
            "32584.01"
          ],
          "rowNumber": 1805996,
          "rowPosition": 1805997,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1805997\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50328",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "29545",
            "1",
            "8",
            "687",
            "14824",
            "91236",
            "368819",
            "75193",
            "889",
            "1831348",
            "2970",
            "1760",
            "2022",
            "2022-05-11",
            "0.0000",
            "2764480.0000",
            "2764480.00",
            "1664930.0000",
            "1664930.00",
            "1664930.00"
          ],
          "rowNumber": 1807702,
          "rowPosition": 1807703,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807703\" violates the foreign key: for \"id_contrato\": values \"75193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43945",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "23316",
            "1",
            "10",
            "412",
            "2589",
            "151873",
            "368791",
            "75199",
            "889",
            "1831307",
            "2586",
            "1760",
            "2022",
            "2022-05-11",
            "230000.0000",
            "4.6000",
            "1058000.00",
            "3.0000",
            "690000.00",
            "690000.00"
          ],
          "rowNumber": 1807704,
          "rowPosition": 1807705,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75199\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1807705\" violates the foreign key: for \"id_contrato\": values \"75199\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43968",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "876",
            "21226",
            "1",
            "13",
            "291",
            "10067",
            "224672",
            "367848",
            "75181",
            "889",
            "1831958",
            "3019",
            "3141",
            "2022",
            "2022-04-27",
            "1.0000",
            "307000.0000",
            "307000.00",
            "280000.0000",
            "280000.00",
            "280000.00"
          ],
          "rowNumber": 1810003,
          "rowPosition": 1810004,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75181\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1810004\" violates the foreign key: for \"id_contrato\": values \"75181\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50357",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "30801",
            "1",
            "3",
            "7",
            "17166",
            "168106",
            "368892",
            "75209",
            "889",
            "1831295",
            "2584",
            "2082",
            "2022",
            "2022-05-11",
            "2.0000",
            "2836.0000",
            "5672.00",
            "2836.0000",
            "5672.00",
            "5672.00"
          ],
          "rowNumber": 1811672,
          "rowPosition": 1811673,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75209\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811673\" violates the foreign key: for \"id_contrato\": values \"75209\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50357",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "30801",
            "1",
            "24",
            "155",
            "8289",
            "241282",
            "368892",
            "75209",
            "582",
            "1831203",
            "2584",
            "2082",
            "2022",
            "2022-05-11",
            "4.0000",
            "334.4300",
            "1337.72",
            "420.0000",
            "1680.00",
            "1680.00"
          ],
          "rowNumber": 1811673,
          "rowPosition": 1811674,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75209\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811674\" violates the foreign key: for \"id_contrato\": values \"75209\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50357",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "30801",
            "1",
            "3",
            "306",
            "12537",
            "145471",
            "368892",
            "75209",
            "889",
            "1831295",
            "2584",
            "2082",
            "2022",
            "2022-05-11",
            "20.0000",
            "200.0000",
            "4000.00",
            "65.5000",
            "1310.00",
            "1310.00"
          ],
          "rowNumber": 1811674,
          "rowPosition": 1811675,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75209\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811675\" violates the foreign key: for \"id_contrato\": values \"75209\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44008",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "368593",
            "75185",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-05-09",
            "12.0000",
            "4921.1000",
            "59053.20",
            "4921.1000",
            "59053.20",
            "59053.20"
          ],
          "rowNumber": 1811696,
          "rowPosition": 1811697,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75185\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811697\" violates the foreign key: for \"id_contrato\": values \"75185\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "535",
            "2147",
            "122547",
            "368615",
            "75204",
            "889",
            "1831991",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "2.0000",
            "4300.0000",
            "8600.00",
            "4728.0800",
            "9456.16",
            "9456.16"
          ],
          "rowNumber": 1811711,
          "rowPosition": 1811712,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811712\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "248",
            "20376",
            "336202",
            "368615",
            "75204",
            "889",
            "1831991",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "2.0000",
            "21406.4100",
            "42812.82",
            "11262.4400",
            "22524.88",
            "22524.88"
          ],
          "rowNumber": 1811712,
          "rowPosition": 1811713,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811713\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "30",
            "173",
            "12392",
            "148606",
            "368615",
            "75204",
            "889",
            "1831354",
            "2670",
            "2045",
            "2022",
            "2022-05-09",
            "0.0000",
            "17419.3500",
            "17419.35",
            "13772.2400",
            "13772.24",
            "13772.24"
          ],
          "rowNumber": 1811713,
          "rowPosition": 1811714,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811714\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "30",
            "173",
            "12392",
            "168220",
            "368615",
            "75204",
            "889",
            "1831354",
            "2670",
            "2045",
            "2022",
            "2022-05-09",
            "0.0000",
            "28475.3200",
            "28475.32",
            "21380.0000",
            "21380.00",
            "21380.00"
          ],
          "rowNumber": 1811714,
          "rowPosition": 1811715,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811715\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "77",
            "533",
            "9643",
            "90741",
            "368615",
            "75204",
            "889",
            "1831749",
            "2738",
            "2045",
            "2022",
            "2022-05-09",
            "0.0000",
            "36000.0000",
            "36000.00",
            "36000.0000",
            "36000.00",
            "36000.00"
          ],
          "rowNumber": 1811715,
          "rowPosition": 1811716,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811716\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "535",
            "18171",
            "182199",
            "368615",
            "75204",
            "889",
            "1831991",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "16841.0000",
            "16841.00",
            "9368.1900",
            "9368.19",
            "9368.19"
          ],
          "rowNumber": 1811716,
          "rowPosition": 1811717,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811717\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "535",
            "2147",
            "182192",
            "368615",
            "75204",
            "889",
            "1831991",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "3.0000",
            "3476.1100",
            "10428.32",
            "1910.6600",
            "5731.98",
            "5731.98"
          ],
          "rowNumber": 1811717,
          "rowPosition": 1811718,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811718\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "19",
            "330",
            "13164",
            "163199",
            "368615",
            "75204",
            "889",
            "1831825",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "27829.1200",
            "27829.12",
            "16254.2000",
            "16254.20",
            "16254.20"
          ],
          "rowNumber": 1811718,
          "rowPosition": 1811719,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811719\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "62",
            "158",
            "3430",
            "340035",
            "368615",
            "75204",
            "889",
            "1831308",
            "2995",
            "2045",
            "2022",
            "2022-05-09",
            "16.0000",
            "1991.8200",
            "31869.12",
            "937.5000",
            "15000.00",
            "15000.00"
          ],
          "rowNumber": 1811719,
          "rowPosition": 1811720,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811720\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "176",
            "4783",
            "121300",
            "368615",
            "75204",
            "889",
            "1831304",
            "2743",
            "2045",
            "2022",
            "2022-05-09",
            "3.0000",
            "15202.7100",
            "45608.13",
            "8350.3100",
            "25050.93",
            "25050.93"
          ],
          "rowNumber": 1811720,
          "rowPosition": 1811721,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811721\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "44",
            "724",
            "15676",
            "147582",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "13.0000",
            "2943.4700",
            "38265.11",
            "2122.4500",
            "27591.85",
            "27591.85"
          ],
          "rowNumber": 1811721,
          "rowPosition": 1811722,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811722\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "452",
            "5574",
            "17347",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "6559.2400",
            "6559.23",
            "9141.7500",
            "9141.75",
            "9141.75"
          ],
          "rowNumber": 1811722,
          "rowPosition": 1811723,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811723\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "89",
            "437",
            "7956",
            "335942",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "2.0000",
            "10638.5000",
            "21277.00",
            "9746.2400",
            "19492.48",
            "19492.48"
          ],
          "rowNumber": 1811723,
          "rowPosition": 1811724,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811724\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "44",
            "724",
            "15676",
            "335943",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "6151.5100",
            "6151.51",
            "3021.6600",
            "3021.66",
            "3021.66"
          ],
          "rowNumber": 1811724,
          "rowPosition": 1811725,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811725\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "75",
            "227",
            "5271",
            "265887",
            "368615",
            "75204",
            "889",
            "1831304",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "2.0000",
            "7139.6800",
            "14279.37",
            "6393.3000",
            "12786.60",
            "12786.60"
          ],
          "rowNumber": 1811725,
          "rowPosition": 1811726,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811726\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "83",
            "511",
            "13373",
            "338783",
            "368615",
            "75204",
            "889",
            "1831825",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "54536.3200",
            "54536.32",
            "39606.5600",
            "39606.56",
            "39606.56"
          ],
          "rowNumber": 1811726,
          "rowPosition": 1811727,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811727\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "77",
            "533",
            "9643",
            "90741",
            "368615",
            "75204",
            "889",
            "1831749",
            "2738",
            "2045",
            "2022",
            "2022-05-09",
            "0.0000",
            "20583.0000",
            "20583.00",
            "18000.0000",
            "18000.00",
            "18000.00"
          ],
          "rowNumber": 1811727,
          "rowPosition": 1811728,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811728\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "41",
            "806",
            "9790",
            "93617",
            "368615",
            "75204",
            "889",
            "1831435",
            "2594",
            "2045",
            "2022",
            "2022-05-09",
            "0.0000",
            "5782.0000",
            "5782.00",
            "10000.0000",
            "10000.00",
            "10000.00"
          ],
          "rowNumber": 1811728,
          "rowPosition": 1811729,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811729\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "67",
            "738",
            "21386",
            "167268",
            "368615",
            "75204",
            "889",
            "1831979",
            "2554",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "3386.7300",
            "3386.73",
            "4112.6200",
            "4112.62",
            "4112.62"
          ],
          "rowNumber": 1811729,
          "rowPosition": 1811730,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811730\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "44",
            "102",
            "5459",
            "337784",
            "368615",
            "75204",
            "889",
            "1831992",
            "2540",
            "2045",
            "2022",
            "2022-05-09",
            "7.0000",
            "599.0000",
            "4193.00",
            "693.0700",
            "4851.49",
            "4851.49"
          ],
          "rowNumber": 1811730,
          "rowPosition": 1811731,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811731\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "237",
            "9638",
            "182053",
            "368615",
            "75204",
            "889",
            "1831295",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "3.0000",
            "2822.5000",
            "8467.50",
            "2373.4500",
            "7120.35",
            "7120.35"
          ],
          "rowNumber": 1811731,
          "rowPosition": 1811732,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811732\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "237",
            "3945",
            "336228",
            "368615",
            "75204",
            "889",
            "1831295",
            "2584",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "11534.0000",
            "11534.00",
            "7460.8200",
            "7460.82",
            "7460.82"
          ],
          "rowNumber": 1811732,
          "rowPosition": 1811733,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811733\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "627",
            "21933",
            "193343",
            "368615",
            "75204",
            "889",
            "1831295",
            "2611",
            "2045",
            "2022",
            "2022-05-09",
            "5.0000",
            "2421.2900",
            "12106.45",
            "1406.4000",
            "7032.00",
            "7032.00"
          ],
          "rowNumber": 1811733,
          "rowPosition": 1811734,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811734\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "627",
            "19215",
            "336224",
            "368615",
            "75204",
            "889",
            "1831295",
            "2611",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "8989.7700",
            "8989.77",
            "5222.5800",
            "5222.58",
            "5222.58"
          ],
          "rowNumber": 1811734,
          "rowPosition": 1811735,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811735\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "627",
            "19215",
            "338797",
            "368615",
            "75204",
            "889",
            "1831295",
            "2611",
            "2045",
            "2022",
            "2022-05-09",
            "12.0000",
            "5437.5000",
            "65250.00",
            "5065.3800",
            "60784.56",
            "60784.56"
          ],
          "rowNumber": 1811735,
          "rowPosition": 1811736,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811736\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "627",
            "19215",
            "336230",
            "368615",
            "75204",
            "889",
            "1831295",
            "2611",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "7075.0000",
            "7075.00",
            "8264.0800",
            "8264.08",
            "8264.08"
          ],
          "rowNumber": 1811736,
          "rowPosition": 1811737,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811737\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "143",
            "18489",
            "226205",
            "368615",
            "75204",
            "889",
            "1831295",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "14.0000",
            "4775.5000",
            "66856.93",
            "2634.8700",
            "36888.18",
            "36888.18"
          ],
          "rowNumber": 1811737,
          "rowPosition": 1811738,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811738\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "143",
            "18489",
            "336204",
            "368615",
            "75204",
            "889",
            "1831295",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "71716.5000",
            "71716.50",
            "67214.2300",
            "67214.23",
            "67214.23"
          ],
          "rowNumber": 1811738,
          "rowPosition": 1811739,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811739\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "237",
            "7897",
            "331426",
            "368615",
            "75204",
            "889",
            "1831295",
            "3018",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "1786.2100",
            "1786.21",
            "1124.5700",
            "1124.57",
            "1124.57"
          ],
          "rowNumber": 1811739,
          "rowPosition": 1811740,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811740\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "284",
            "4710",
            "116004",
            "368615",
            "75204",
            "889",
            "1831295",
            "2611",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "521.4500",
            "521.45",
            "1227.3400",
            "1227.34",
            "1227.34"
          ],
          "rowNumber": 1811740,
          "rowPosition": 1811741,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811741\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43948",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "33472",
            "1",
            "3",
            "627",
            "16366",
            "336401",
            "368615",
            "75204",
            "889",
            "1831295",
            "2611",
            "2045",
            "2022",
            "2022-05-09",
            "1.0000",
            "4399.0000",
            "4399.00",
            "8694.9500",
            "8694.95",
            "8694.95"
          ],
          "rowNumber": 1811741,
          "rowPosition": 1811742,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1811742\" violates the foreign key: for \"id_contrato\": values \"75204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50293",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "386",
            "1",
            "77",
            "73",
            "20205",
            "92481",
            "364603",
            "75187",
            "889",
            "1831761",
            "2872",
            "1760",
            "2021",
            "2022-02-25",
            "0.0000",
            "387942.1700",
            "387942.17",
            "387942.1700",
            "387942.17",
            "387942.17"
          ],
          "rowNumber": 1815184,
          "rowPosition": 1815185,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75187\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815185\" violates the foreign key: for \"id_contrato\": values \"75187\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50279",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "36598",
            "1",
            "42",
            "104",
            "100",
            "171172",
            "366578",
            "75201",
            "889",
            "1831334",
            "2813",
            "2081",
            "2021",
            "2022-04-04",
            "1.0000",
            "151661.0000",
            "151661.00",
            "217530.0000",
            "217530.00",
            "0.00"
          ],
          "rowNumber": 1825962,
          "rowPosition": 1825963,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825963\" violates the foreign key: for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50279",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "36598",
            "1",
            "42",
            "104",
            "11874",
            "196680",
            "366578",
            "75201",
            "889",
            "1831334",
            "2813",
            "2081",
            "2021",
            "2022-04-04",
            "3.0000",
            "94013.0000",
            "282039.00",
            "77153.0000",
            "231459.00",
            "0.00"
          ],
          "rowNumber": 1825963,
          "rowPosition": 1825964,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825964\" violates the foreign key: for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50279",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "36598",
            "1",
            "42",
            "104",
            "100",
            "163171",
            "366578",
            "75201",
            "889",
            "1831334",
            "2813",
            "2081",
            "2021",
            "2022-04-04",
            "1.0000",
            "295000.0000",
            "295000.00",
            "240997.0000",
            "240997.00",
            "0.00"
          ],
          "rowNumber": 1825964,
          "rowPosition": 1825965,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825965\" violates the foreign key: for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "1",
            "1831070",
            "66",
            "1",
            "1",
            "66",
            "71130",
            "1",
            "77",
            "533",
            "4338",
            "301708",
            "369566",
            "75171",
            "889",
            "1831751",
            "2807",
            "3083",
            "2022",
            "2022-05-19",
            "0.0000",
            "8500.0000",
            "8500.00",
            "8500.0000",
            "8500.00",
            "8500.00"
          ],
          "rowNumber": 1828423,
          "rowPosition": 1828424,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828424\" violates the foreign key: for \"id_contrato\": values \"75171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44010",
            "1",
            "1831070",
            "66",
            "1",
            "1",
            "66",
            "71130",
            "1",
            "77",
            "533",
            "4338",
            "301708",
            "369566",
            "75171",
            "889",
            "1831751",
            "2807",
            "3083",
            "2022",
            "2022-05-19",
            "0.0000",
            "8500.0000",
            "8500.00",
            "8500.0000",
            "8500.00",
            "8500.00"
          ],
          "rowNumber": 1828423,
          "rowPosition": 1828424,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"71130\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1828424\" violates the foreign key: for \"id_contratado\": values \"71130\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43996",
            "15",
            "1831047",
            "37",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "2941",
            "5465",
            "369206",
            "75200",
            "190",
            "1831313",
            "2928",
            "3044",
            "2022",
            "2022-05-16",
            "3000.0000",
            "4.8200",
            "14460.90",
            "4.8200",
            "14460.90",
            "14460.90"
          ],
          "rowNumber": 1829344,
          "rowPosition": 1829345,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75200\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829345\" violates the foreign key: for \"id_contrato\": values \"75200\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "29765",
            "1",
            "3",
            "627",
            "19215",
            "275597",
            "368226",
            "75168",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-05-03",
            "3.0000",
            "4693.4800",
            "14080.44",
            "4693.4800",
            "14080.44",
            "14080.44"
          ],
          "rowNumber": 1829777,
          "rowPosition": 1829778,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75168\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829778\" violates the foreign key: for \"id_contrato\": values \"75168\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44015",
            "15",
            "1831095",
            "96",
            "1",
            "1",
            "856",
            "66423",
            "1",
            "9",
            "378",
            "20112",
            "260551",
            "369163",
            "75169",
            "322",
            "1831948",
            "2668",
            "3293",
            "2022",
            "2022-05-16",
            "72.0000",
            "5002.7200",
            "360195.84",
            "5002.7200",
            "360195.84",
            "360195.84"
          ],
          "rowNumber": 1829940,
          "rowPosition": 1829941,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1829941\" violates the foreign key: for \"id_contrato\": values \"75169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "19147",
            "1",
            "9",
            "576",
            "17555",
            "91211",
            "369427",
            "75203",
            "889",
            "1831701",
            "2736",
            "2014",
            "2022",
            "2022-05-18",
            "0.0000",
            "1620.0000",
            "1620.00",
            "1620.0000",
            "1620.00",
            "1620.00"
          ],
          "rowNumber": 1830402,
          "rowPosition": 1830403,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830403\" violates the foreign key: for \"id_contrato\": values \"75203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "19147",
            "1",
            "9",
            "576",
            "17555",
            "91211",
            "369427",
            "75203",
            "889",
            "1831701",
            "2736",
            "2014",
            "2022",
            "2022-05-18",
            "0.0000",
            "5400.0000",
            "5400.00",
            "5400.0000",
            "5400.00",
            "5400.00"
          ],
          "rowNumber": 1830403,
          "rowPosition": 1830404,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830404\" violates the foreign key: for \"id_contrato\": values \"75203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "19147",
            "1",
            "9",
            "576",
            "17555",
            "91211",
            "369427",
            "75203",
            "889",
            "1831701",
            "2736",
            "2014",
            "2022",
            "2022-05-18",
            "0.0000",
            "2700.0000",
            "2700.00",
            "2700.0000",
            "2700.00",
            "2700.00"
          ],
          "rowNumber": 1830404,
          "rowPosition": 1830405,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830405\" violates the foreign key: for \"id_contrato\": values \"75203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "19147",
            "1",
            "9",
            "576",
            "17555",
            "91211",
            "369427",
            "75203",
            "889",
            "1831701",
            "2736",
            "2014",
            "2022",
            "2022-05-18",
            "0.0000",
            "11700.0000",
            "11700.00",
            "11700.0000",
            "11700.00",
            "11700.00"
          ],
          "rowNumber": 1830405,
          "rowPosition": 1830406,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830406\" violates the foreign key: for \"id_contrato\": values \"75203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43973",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "19147",
            "1",
            "9",
            "576",
            "17555",
            "91211",
            "369427",
            "75203",
            "889",
            "1831701",
            "2736",
            "2014",
            "2022",
            "2022-05-18",
            "0.0000",
            "39000.0000",
            "39000.00",
            "39000.0000",
            "39000.00",
            "39000.00"
          ],
          "rowNumber": 1830406,
          "rowPosition": 1830407,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1830407\" violates the foreign key: for \"id_contrato\": values \"75203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "37421",
            "1",
            "87",
            "221",
            "14496",
            "281810",
            "369368",
            "75208",
            "889",
            "1831968",
            "2554",
            "2081",
            "2022",
            "2022-05-17",
            "10.0000",
            "2306.5000",
            "23065.00",
            "1500.0000",
            "15000.00",
            "15000.00"
          ],
          "rowNumber": 1832643,
          "rowPosition": 1832644,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832644\" violates the foreign key: for \"id_contrato\": values \"75208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43975",
            "14",
            "1831009",
            "1",
            "1",
            "1",
            "66",
            "62670",
            "1",
            "51",
            "74",
            "9661",
            "91085",
            "369274",
            "75180",
            "889",
            "1831504",
            "2670",
            "2413",
            "2022",
            "2022-05-17",
            "0.0000",
            "2035.0000",
            "2035.00",
            "2030.0000",
            "2030.00",
            "2030.00"
          ],
          "rowNumber": 1833175,
          "rowPosition": 1833176,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833176\" violates the foreign key: for \"id_contrato\": values \"75180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50359",
            "4",
            "1831079",
            "76",
            "1",
            "1",
            "66",
            "28327",
            "1",
            "56",
            "527",
            "20558",
            "125204",
            "367613",
            "75170",
            "889",
            "1831940",
            "2814",
            "2046",
            "2022",
            "2022-04-20",
            "3.0000",
            "4390.0000",
            "13170.00",
            "3150.0000",
            "9450.00",
            "9450.00"
          ],
          "rowNumber": 1833647,
          "rowPosition": 1833648,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75170\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833648\" violates the foreign key: for \"id_contrato\": values \"75170\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50359",
            "4",
            "1831079",
            "76",
            "1",
            "1",
            "66",
            "68566",
            "1",
            "75",
            "227",
            "5271",
            "132931",
            "367613",
            "75174",
            "889",
            "1831846",
            "3018",
            "2046",
            "2022",
            "2022-04-20",
            "12.0000",
            "2307.1400",
            "27685.68",
            "1875.0000",
            "22500.00",
            "22500.00"
          ],
          "rowNumber": 1833648,
          "rowPosition": 1833649,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75174\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833649\" violates the foreign key: for \"id_contrato\": values \"75174\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50359",
            "4",
            "1831079",
            "76",
            "1",
            "1",
            "66",
            "66530",
            "1",
            "60",
            "513",
            "14408",
            "211386",
            "367613",
            "75190",
            "889",
            "1831952",
            "2742",
            "2046",
            "2022",
            "2022-04-20",
            "112.0000",
            "6361.2000",
            "712454.40",
            "6214.0000",
            "695968.00",
            "695968.00"
          ],
          "rowNumber": 1833649,
          "rowPosition": 1833650,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75190\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833650\" violates the foreign key: for \"id_contrato\": values \"75190\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50359",
            "4",
            "1831079",
            "76",
            "1",
            "1",
            "66",
            "66530",
            "1",
            "54",
            "424",
            "9312",
            "125444",
            "367613",
            "75190",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-04-20",
            "3.0000",
            "912.0000",
            "2736.00",
            "912.0000",
            "2736.00",
            "2736.00"
          ],
          "rowNumber": 1833655,
          "rowPosition": 1833656,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75190\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833656\" violates the foreign key: for \"id_contrato\": values \"75190\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50359",
            "4",
            "1831079",
            "76",
            "1",
            "1",
            "66",
            "21480",
            "1",
            "54",
            "427",
            "3990",
            "147012",
            "367613",
            "75179",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-04-20",
            "15.0000",
            "1380.0000",
            "20700.00",
            "1380.0000",
            "20700.00",
            "20700.00"
          ],
          "rowNumber": 1833656,
          "rowPosition": 1833657,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75179\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833657\" violates the foreign key: for \"id_contrato\": values \"75179\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43969",
            "15",
            "1831008",
            "5",
            "1",
            "1",
            "856",
            "66423",
            "1",
            "9",
            "378",
            "20112",
            "260549",
            "366291",
            "75186",
            "322",
            "1831948",
            "2668",
            "2925",
            "2022",
            "2022-03-31",
            "288.0000",
            "2460.9200",
            "708744.96",
            "2460.9200",
            "708744.96",
            "708744.96"
          ],
          "rowNumber": 1834466,
          "rowPosition": 1834467,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75186\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1834467\" violates the foreign key: for \"id_contrato\": values \"75186\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43967",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "26032",
            "1",
            "77",
            "533",
            "14912",
            "104380",
            "368510",
            "75197",
            "889",
            "1831582",
            "2738",
            "1760",
            "2022",
            "2022-05-06",
            "0.0000",
            "54617.0000",
            "54617.00",
            "52456.0000",
            "52456.00",
            "52456.00"
          ],
          "rowNumber": 1834876,
          "rowPosition": 1834877,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75197\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1834877\" violates the foreign key: for \"id_contrato\": values \"75197\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44016",
            "14",
            "1831034",
            "50",
            "1",
            "8",
            "352",
            "71148",
            "1",
            "77",
            "808",
            "4383",
            "91625",
            "369645",
            "46296",
            "889",
            "1831737",
            "2869",
            "1760",
            "2022",
            "2022-05-20",
            "0.0000",
            "2883.0000",
            "2883.00",
            "2883.0000",
            "2883.00",
            "2883.00"
          ],
          "rowNumber": 1837595,
          "rowPosition": 1837596,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"71148\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1837596\" violates the foreign key: for \"id_contratado\": values \"71148\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50364",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "55950",
            "1",
            "77",
            "273",
            "14784",
            "90078",
            "368718",
            "75191",
            "889",
            "1831537",
            "2954",
            "1760",
            "2022",
            "2022-05-10",
            "0.0000",
            "163625.8900",
            "163625.89",
            "41955.3600",
            "41955.36",
            "41955.36"
          ],
          "rowNumber": 1837778,
          "rowPosition": 1837779,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1837779\" violates the foreign key: for \"id_contrato\": values \"75191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50345",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "65933",
            "1",
            "54",
            "502",
            "6435",
            "238653",
            "368280",
            "75177",
            "889",
            "1831296",
            "2944",
            "1760",
            "2022",
            "2022-05-10",
            "1125.0000",
            "359.7200",
            "404685.00",
            "286.0000",
            "321750.00",
            "321750.00"
          ],
          "rowNumber": 1837780,
          "rowPosition": 1837781,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75177\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1837781\" violates the foreign key: for \"id_contrato\": values \"75177\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44011",
            "15",
            "1831096",
            "92",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "16006",
            "118342",
            "368977",
            "75202",
            "190",
            "1831313",
            "2928",
            "2631",
            "2022",
            "2022-05-12",
            "2000.0000",
            "5.2400",
            "10479.00",
            "5.2400",
            "10479.00",
            "10479.00"
          ],
          "rowNumber": 1837854,
          "rowPosition": 1837855,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1837855\" violates the foreign key: for \"id_contrato\": values \"75202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44011",
            "15",
            "1831096",
            "92",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "2941",
            "5465",
            "368977",
            "75202",
            "190",
            "1831313",
            "2928",
            "2631",
            "2022",
            "2022-05-12",
            "39000.0000",
            "4.8200",
            "187991.70",
            "4.8200",
            "187991.70",
            "187991.70"
          ],
          "rowNumber": 1837855,
          "rowPosition": 1837856,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1837856\" violates the foreign key: for \"id_contrato\": values \"75202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43989",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "637",
            "69374",
            "1",
            "77",
            "808",
            "4383",
            "91625",
            "368937",
            "75183",
            "889",
            "1899033",
            "2869",
            "3043",
            "2022",
            "2022-05-12",
            "0.0000",
            "114220.0000",
            "114220.00",
            "48475.0000",
            "48475.00",
            "48475.00"
          ],
          "rowNumber": 1837860,
          "rowPosition": 1837861,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1837861\" violates the foreign key: for \"id_contrato\": values \"75183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43989",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "637",
            "69374",
            "1",
            "77",
            "808",
            "4383",
            "91625",
            "368937",
            "75183",
            "889",
            "1899033",
            "2869",
            "3043",
            "2022",
            "2022-05-12",
            "0.0000",
            "36600.0000",
            "36600.00",
            "53461.0000",
            "53461.00",
            "53461.00"
          ],
          "rowNumber": 1837862,
          "rowPosition": 1837863,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1837863\" violates the foreign key: for \"id_contrato\": values \"75183\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44017",
            "14",
            "1831105",
            "50",
            "1",
            "8",
            "857",
            "71141",
            "1",
            "77",
            "533",
            "1911",
            "92793",
            "369619",
            "46296",
            "889",
            "1831555",
            "3136",
            "3042",
            "2022",
            "2022-05-20",
            "0.0000",
            "2200.0000",
            "2200.00",
            "2200.0000",
            "2200.00",
            "2200.00"
          ],
          "rowNumber": 1837925,
          "rowPosition": 1837926,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"71141\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1837926\" violates the foreign key: for \"id_contratado\": values \"71141\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50279",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "36598",
            "1",
            "42",
            "104",
            "100",
            "163171",
            "366578",
            "75201",
            "889",
            "1831415",
            "2813",
            "2081",
            "2021",
            "2022-04-04",
            "0.0000",
            "295000.0000",
            "0.00",
            "240997.0000",
            "0.00",
            "240997.00"
          ],
          "rowNumber": 1837946,
          "rowPosition": 1837947,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1837947\" violates the foreign key: for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50279",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "36598",
            "1",
            "42",
            "104",
            "11874",
            "196680",
            "366578",
            "75201",
            "889",
            "1831415",
            "2813",
            "2081",
            "2021",
            "2022-04-04",
            "0.0000",
            "94013.0000",
            "0.00",
            "77153.0000",
            "0.00",
            "231459.00"
          ],
          "rowNumber": 1837947,
          "rowPosition": 1837948,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1837948\" violates the foreign key: for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50279",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "36598",
            "1",
            "42",
            "104",
            "100",
            "171172",
            "366578",
            "75201",
            "889",
            "1831415",
            "2813",
            "2081",
            "2021",
            "2022-04-04",
            "0.0000",
            "151661.0000",
            "0.00",
            "217530.0000",
            "0.00",
            "217530.00"
          ],
          "rowNumber": 1837948,
          "rowPosition": 1837949,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1837949\" violates the foreign key: for \"id_contrato\": values \"75201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44018",
            "14",
            "1831034",
            "50",
            "1",
            "8",
            "66",
            "71137",
            "1",
            "51",
            "374",
            "20260",
            "93213",
            "369615",
            "46296",
            "889",
            "1831362",
            "2545",
            "1760",
            "2022",
            "2022-05-20",
            "0.0000",
            "880.0000",
            "880.00",
            "880.0000",
            "880.00",
            "880.00"
          ],
          "rowNumber": 1838644,
          "rowPosition": 1838645,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"71137\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1838645\" violates the foreign key: for \"id_contratado\": values \"71137\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43974",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "821",
            "55586",
            "1",
            "9",
            "576",
            "9436",
            "186633",
            "368767",
            "75205",
            "889",
            "1831365",
            "2736",
            "3043",
            "2022",
            "2022-05-10",
            "0.0000",
            "23040.0000",
            "23040.00",
            "34560.0000",
            "34560.00",
            "34560.00"
          ],
          "rowNumber": 1840330,
          "rowPosition": 1840331,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1840331\" violates the foreign key: for \"id_contrato\": values \"75205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43974",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "821",
            "55586",
            "1",
            "9",
            "576",
            "9436",
            "186638",
            "368767",
            "75205",
            "889",
            "1831365",
            "2736",
            "3043",
            "2022",
            "2022-05-10",
            "0.0000",
            "23040.0000",
            "23040.00",
            "7200.0000",
            "7200.00",
            "7200.00"
          ],
          "rowNumber": 1840331,
          "rowPosition": 1840332,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1840332\" violates the foreign key: for \"id_contrato\": values \"75205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43998",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "825",
            "1488",
            "1",
            "51",
            "75",
            "12410",
            "158735",
            "368950",
            "75196",
            "889",
            "1831642",
            "2594",
            "3955",
            "2022",
            "2022-05-12",
            "0.0000",
            "856615.5100",
            "856615.51",
            "849000.0000",
            "849000.00",
            "849000.00"
          ],
          "rowNumber": 1840346,
          "rowPosition": 1840347,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75196\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1840347\" violates the foreign key: for \"id_contrato\": values \"75196\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43995",
            "14",
            "1831041",
            "41",
            "1",
            "1",
            "883",
            "68269",
            "1",
            "69",
            "446",
            "21581",
            "170046",
            "368985",
            "75172",
            "1544",
            "1831312",
            "2538",
            "2689",
            "2022",
            "2022-05-12",
            "100.0000",
            "20.9900",
            "2099.00",
            "18.5000",
            "1850.00",
            "1850.00"
          ],
          "rowNumber": 1840353,
          "rowPosition": 1840354,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75172\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1840354\" violates the foreign key: for \"id_contrato\": values \"75172\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "48931",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "32547",
            "1",
            "42",
            "399",
            "1388",
            "50150",
            "368926",
            "75206",
            "889",
            "1831334",
            "2923",
            "2014",
            "2021",
            "2022-05-12",
            "12.0000",
            "5700.0000",
            "68400.00",
            "5695.0200",
            "68340.24",
            "68340.24"
          ],
          "rowNumber": 1840538,
          "rowPosition": 1840539,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1840539\" violates the foreign key: for \"id_contrato\": values \"75206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "48931",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "32547",
            "1",
            "42",
            "399",
            "6545",
            "51031",
            "368926",
            "75206",
            "889",
            "1831334",
            "2923",
            "2014",
            "2021",
            "2022-05-12",
            "12.0000",
            "350.0000",
            "4200.00",
            "129.9800",
            "1559.76",
            "1559.76"
          ],
          "rowNumber": 1840539,
          "rowPosition": 1840540,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1840540\" violates the foreign key: for \"id_contrato\": values \"75206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "48931",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "32547",
            "1",
            "42",
            "399",
            "1388",
            "50149",
            "368926",
            "75206",
            "889",
            "1831334",
            "2923",
            "2014",
            "2021",
            "2022-05-12",
            "96.0000",
            "3700.0000",
            "355200.00",
            "3920.0200",
            "376321.92",
            "376321.92"
          ],
          "rowNumber": 1840540,
          "rowPosition": 1840541,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1840541\" violates the foreign key: for \"id_contrato\": values \"75206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "48931",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "32547",
            "1",
            "42",
            "399",
            "6545",
            "136703",
            "368926",
            "75206",
            "889",
            "1831334",
            "2923",
            "2014",
            "2021",
            "2022-05-12",
            "96.0000",
            "350.0000",
            "33600.00",
            "129.9800",
            "12478.08",
            "12478.08"
          ],
          "rowNumber": 1840541,
          "rowPosition": 1840542,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1840542\" violates the foreign key: for \"id_contrato\": values \"75206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "48931",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "32547",
            "1",
            "42",
            "399",
            "17466",
            "86596",
            "368926",
            "75206",
            "889",
            "1831334",
            "2923",
            "2014",
            "2021",
            "2022-05-12",
            "96.0000",
            "1416.0000",
            "135936.00",
            "493.5000",
            "47376.00",
            "47376.00"
          ],
          "rowNumber": 1840542,
          "rowPosition": 1840543,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1840543\" violates the foreign key: for \"id_contrato\": values \"75206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "50268",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "5470",
            "1",
            "51",
            "383",
            "17638",
            "94053",
            "368991",
            "75184",
            "981",
            "1831360",
            "2670",
            "2014",
            "2021",
            "2022-05-12",
            "0.0000",
            "71800.0000",
            "71800.00",
            "39299.7600",
            "39299.76",
            "39299.76"
          ],
          "rowNumber": 1840779,
          "rowPosition": 1840780,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"75184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1840780\" violates the foreign key: for \"id_contrato\": values \"75184\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 120
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 120,
    "tasks": 1
  },
  "valid": false
}